// The daily rulebook for cafe owners and staff, in English, Hindi and Hinglish.
// Each step can show the real button (btn) and open the real page (go).
const T = (en, hi, hg) => ({ en, hi, hg });

export const SOP = [
    {
        id: 'open', icon: '🌅', when: T('Every morning', 'हर सुबह', 'Har subah'),
        title: T('Opening the cafe', 'कैफ़े खोलना', 'Cafe kholna'),
        intro: T('Before the first customer: log in, check in, and open the cash drawer.',
            'पहले ग्राहक से पहले: लॉगिन करें, हाज़िरी लगाएँ और कैश ड्रॉअर खोलें।',
            'Pehle customer se pehle: login karo, haaziri lagao aur cash drawer kholo.'),
        steps: [
            { t: T('Open the app on the counter phone or laptop and log in with your mobile number and PIN.',
                'काउंटर के फ़ोन या लैपटॉप पर ऐप खोलें और अपने मोबाइल नंबर और PIN से लॉगिन करें।',
                'Counter ke phone ya laptop pe app kholo aur apne mobile number aur PIN se login karo.'), btn: 'Staff PIN', go: '/admin/login' },
            { t: T('Go to My day and tap Check in. Stand inside the cafe: the app checks your location.',
                'मेरा दिन में जाएँ और Check in दबाएँ। कैफ़े के अंदर खड़े रहें: ऐप आपकी लोकेशन देखता है।',
                'My day mein jao aur Check in dabao. Cafe ke andar khade raho: app location check karta hai.'), btn: 'Check in', go: '/admin/me' },
            { t: T('Go to Cash & Shifts, tap Open shift, count the notes in the drawer and type the opening cash.',
                'कैश और शिफ्ट में जाएँ, Open shift दबाएँ, ड्रॉअर के नोट गिनें और शुरुआती कैश लिखें।',
                'Cash & Shifts mein jao, Open shift dabao, drawer ke note gino aur opening cash likho.'), btn: 'Open shift', go: '/admin/shifts' },
            { t: T('Turn on the kitchen screen and the pickup TV (they stay logged in).',
                'किचन स्क्रीन और पिकअप टीवी चालू करें (वे लॉगिन रहते हैं)।',
                'Kitchen screen aur pickup TV on karo (woh login rehte hain).'), btn: 'Kitchen', go: '/admin/kitchen' },
            { t: T('Tap the bell 🔔 at the top: read low-stock and other alerts.',
                'ऊपर घंटी 🔔 दबाएँ: कम स्टॉक और बाकी अलर्ट पढ़ें।',
                'Upar ghanti 🔔 dabao: low stock aur baaki alerts padho.'), btn: '🔔' },
        ],
        example: T('Example: Ravi opens at 8 am, logs in, checks in, opens the shift with ₹2,000 in the drawer. The bell says "Milk below reorder point", so he buys milk first.',
            'उदाहरण: रवि सुबह 8 बजे खोलता है, लॉगिन करता है, हाज़िरी लगाता है, ड्रॉअर में ₹2,000 के साथ शिफ्ट खोलता है। घंटी में "दूध कम है" लिखा है, तो वह पहले दूध लाता है।',
            'Example: Ravi subah 8 baje kholta hai, login karta hai, check in karta hai, ₹2,000 ke saath shift kholta hai. Ghanti mein "Milk kam hai" aata hai, toh pehle doodh laata hai.'),
    },
    {
        id: 'counter', perms: ['orders.create'], icon: '🧾', when: T('All day', 'पूरे दिन', 'Poore din'),
        title: T('Taking an order at the counter', 'काउंटर पर ऑर्डर लेना', 'Counter pe order lena'),
        intro: T('For walk-in customers who order and pay at the counter.', 'काउंटर पर आकर ऑर्डर और पेमेंट करने वाले ग्राहकों के लिए।',
            'Jo customer counter pe aakar order aur payment karte hain, unke liye.'),
        steps: [
            { t: T('Open Counter. Choose Takeaway or Dine-in (pick the table for dine-in).', 'काउंटर खोलें। Takeaway या Dine-in चुनें (Dine-in में टेबल चुनें)।',
                'Counter kholo. Takeaway ya Dine-in chuno (Dine-in mein table chuno).'), btn: 'Counter', go: '/admin/pos' },
            { t: T('Type the customer mobile number. You will see their tier (Gold…), 👑 member and 🎂 birthday gift.',
                'ग्राहक का मोबाइल नंबर लिखें। उनका टियर (Gold…), 👑 मेंबर और 🎂 बर्थडे गिफ्ट दिखेगा।',
                'Customer ka mobile number likho. Unka tier (Gold…), 👑 member aur 🎂 birthday gift dikhega.') },
            { t: T('Tap items to add them. If they have a birthday gift, tap 🎂 Apply birthday gift.', 'आइटम दबाकर जोड़ें। बर्थडे गिफ्ट हो तो 🎂 Apply birthday gift दबाएँ।',
                'Items dabake add karo. Birthday gift ho toh 🎂 Apply birthday gift dabao.'), btn: '🎂 Apply birthday gift' },
            { t: T('Discount? Enter it with a reason. A big discount needs a manager PIN.', 'छूट देनी है? कारण के साथ लिखें। बड़ी छूट के लिए मैनेजर PIN चाहिए।',
                'Discount dena hai? Reason ke saath likho. Bada discount ho toh manager PIN lagega.') },
            { t: T('Tap Pay. Choose Cash (type notes received to see change), UPI, Card or Split.', 'Pay दबाएँ। Cash (मिले नोट लिखें, बाकी पैसे दिखेंगे), UPI, Card या Split चुनें।',
                'Pay dabao. Cash (mile hue note likho, change dikhega), UPI, Card ya Split chuno.'), btn: 'Pay' },
            { t: T('Give the token number to the customer. The kitchen and the pickup TV get the order at once.', 'ग्राहक को टोकन नंबर दें। किचन और पिकअप टीवी पर ऑर्डर तुरंत पहुँचता है।',
                'Customer ko token number do. Kitchen aur pickup TV pe order turant pahunchta hai.') },
        ],
        example: T('Example: Meera (Gold) buys 2 coffees. Her number shows "Gold", the bill shows "Gold 5%" off automatically. She pays ₹114 by UPI and gets token 23.',
            'उदाहरण: मीरा (Gold) 2 कॉफ़ी लेती है। उनके नंबर पर "Gold" दिखता है, बिल में अपने-आप "Gold 5%" छूट लगती है। वह ₹114 UPI से देती है और टोकन 23 मिलता है।',
            'Example: Meera (Gold) 2 coffee leti hai. Number daalte hi "Gold" dikhta hai, bill mein apne aap "Gold 5%" lagta hai. ₹114 UPI se deti hai, token 23 milta hai.'),
        tip: T('No internet? Keep selling. Orders wait on the device and go up by themselves when the internet is back.',
            'इंटरनेट नहीं? बेचते रहें। ऑर्डर डिवाइस में रुकते हैं और इंटरनेट आते ही अपने-आप चले जाते हैं।',
            'Internet nahi? Bechte raho. Order device mein rukte hain aur net aate hi apne aap chale jaate hain.'),
    },
    {
        id: 'qr', perms: ['orders.view'], icon: '📱', when: T('All day', 'पूरे दिन', 'Poore din'),
        title: T('QR orders from tables', 'टेबल के QR से ऑर्डर', 'Table ke QR se order'),
        intro: T('Customers scan the QR on their table and order from their phone. You confirm, serve and take payment.',
            'ग्राहक टेबल का QR स्कैन करके फ़ोन से ऑर्डर करते हैं। आप कन्फ़र्म करें, परोसें और पेमेंट लें।',
            'Customer table ka QR scan karke phone se order karte hain. Aap confirm karo, serve karo, payment lo.'),
        steps: [
            { t: T('A new order rings the phone and appears in Orders. Tap Confirm Order.', 'नया ऑर्डर आने पर फ़ोन बजता है और Orders में दिखता है। Confirm Order दबाएँ।',
                'Naya order aate hi phone bajta hai aur Orders mein dikhta hai. Confirm Order dabao.'), btn: 'Confirm Order', go: '/admin/orders' },
            { t: T('"Confirm table" in yellow? It is the first order on that table. Check someone is sitting there, then tap Confirm table.',
                'पीले में "Confirm table"? यह उस टेबल का पहला ऑर्डर है। देखें कोई बैठा है, फिर Confirm table दबाएँ।',
                'Peele mein "Confirm table"? Yeh us table ka pehla order hai. Dekho koi baitha hai, phir Confirm table dabao.'), btn: 'Confirm table' },
            { t: T('Two groups on one table? Each has its own bill. "Table 5 · 2 groups" shows on the order.', 'एक टेबल पर दो ग्रुप? हर ग्रुप का अलग बिल। ऑर्डर पर "Table 5 · 2 groups" दिखता है।',
                'Ek table pe do group? Har group ka alag bill. Order pe "Table 5 · 2 groups" dikhta hai.') },
            { t: T('One person paying for everyone? Tap Whole table for one bill.', 'एक व्यक्ति सबका पैसा दे रहा है? एक बिल के लिए Whole table दबाएँ।',
                'Ek banda sabka pay kar raha hai? Ek bill ke liye Whole table dabao.'), btn: 'Whole table' },
            { t: T('Customers moved tables? Tap Move and choose the new table.', 'ग्राहक ने टेबल बदली? Move दबाकर नई टेबल चुनें।',
                'Customer ne table badli? Move dabao aur nayi table chuno.'), btn: 'Move' },
            { t: T('Take payment: Take payment → method → Paid. The table frees itself when every bill is paid.',
                'पेमेंट: Take payment → तरीका → Paid। सारे बिल भरने पर टेबल अपने-आप खाली हो जाती है।',
                'Payment: Take payment → method → Paid. Saare bill bharne pe table apne aap free ho jaati hai.'), btn: 'Take payment' },
        ],
        example: T('Example: Table 5 has Rahul and Priya ordering on their own phones. Rahul asks for the bill: only his orders go to "bill requested". Priya pays later separately.',
            'उदाहरण: टेबल 5 पर राहुल और प्रिया अपने-अपने फ़ोन से ऑर्डर करते हैं। राहुल बिल माँगता है: सिर्फ़ उसके ऑर्डर "bill requested" होते हैं। प्रिया बाद में अलग से पेमेंट करती है।',
            'Example: Table 5 pe Rahul aur Priya apne phone se order karte hain. Rahul bill maangta hai: sirf uske order "bill requested" hote hain. Priya baad mein alag pay karti hai.'),
    },
    {
        id: 'kitchen', perms: ['orders.view'], icon: '👨‍🍳', when: T('All day', 'पूरे दिन', 'Poore din'),
        title: T('Kitchen and pickup TV', 'किचन और पिकअप टीवी', 'Kitchen aur pickup TV'),
        intro: T('The kitchen marks dishes ready; ready orders flash on the big TV so customers collect them.',
            'किचन डिश तैयार मार्क करता है; तैयार ऑर्डर बड़े टीवी पर चमकते हैं ताकि ग्राहक ले जाएँ।',
            'Kitchen dish ready mark karta hai; ready order bade TV pe chamakte hain taaki customer le jaayein.'),
        steps: [
            { t: T('Kitchen screen: tap a dish when it is done, or All ready for the whole order.', 'किचन स्क्रीन: डिश बनते ही उस पर टैप करें, या पूरे ऑर्डर के लिए All ready।',
                'Kitchen screen: dish bante hi us pe tap karo, ya poore order ke liye All ready.'), btn: 'All ready', go: '/admin/kitchen' },
            { t: T('The pickup TV turns green with the number and plays a chime.', 'पिकअप टीवी नंबर के साथ हरा हो जाता है और घंटी बजती है।',
                'Pickup TV number ke saath green ho jaata hai aur chime bajti hai.') },
            { t: T('When you hand it over, open Pickup screen and tap Collected. The number leaves the TV.', 'ऑर्डर देने पर Pickup screen खोलें और Collected दबाएँ। नंबर टीवी से हट जाता है।',
                'Order dene pe Pickup screen kholo aur Collected dabao. Number TV se hat jaata hai.'), btn: 'Collected', go: '/admin/pickup-screen' },
            { t: T('No kitchen screen? On Pickup screen, tap a number under Preparing to mark it ready.', 'किचन स्क्रीन नहीं है? Pickup screen पर Preparing में नंबर दबाकर तैयार मार्क करें।',
                'Kitchen screen nahi hai? Pickup screen pe Preparing mein number dabake ready mark karo.') },
        ],
        example: T('Example: Q7 is ready. The TV shows a big green "Q7 · Karan". Karan comes, you hand over the tray and tap Collected.',
            'उदाहरण: Q7 तैयार है। टीवी पर बड़ा हरा "Q7 · Karan" आता है। करन आता है, आप ट्रे देते हैं और Collected दबाते हैं।',
            'Example: Q7 ready hai. TV pe bada green "Q7 · Karan" aata hai. Karan aata hai, tray do aur Collected dabao.'),
    },
    {
        id: 'khata', perms: ['customers.view'], icon: '📒', when: T('When needed', 'ज़रूरत पर', 'Zaroorat pe'),
        title: T('Khata (credit) and the kiosk', 'खाता (उधार) और कियोस्क', 'Khata (udhaar) aur kiosk'),
        intro: T('Regulars who pay later, and quick shelf sales at the kiosk.', 'जो रेगुलर बाद में पैसे देते हैं, और कियोस्क पर जल्दी बिक्री।',
            'Jo regular baad mein pay karte hain, aur kiosk pe jaldi bikri.'),
        steps: [
            { t: T('Kiosk: pick the customer, tap items, then Cash, UPI or Khata.', 'कियोस्क: ग्राहक चुनें, आइटम दबाएँ, फिर Cash, UPI या Khata।',
                'Kiosk: customer chuno, items dabao, phir Cash, UPI ya Khata.'), btn: 'Khata', go: '/admin/kiosk' },
            { t: T('Each customer has a credit limit. Above it, a manager must approve.', 'हर ग्राहक की उधार सीमा होती है। उससे ज़्यादा पर मैनेजर की मंज़ूरी चाहिए।',
                'Har customer ki udhaar limit hoti hai. Usse zyada pe manager ki approval chahiye.') },
            { t: T('They come to pay: Khata → their name → Collect → amount → into the drawer.', 'पैसे देने आए: Khata → उनका नाम → Collect → रकम → ड्रॉअर में।',
                'Pay karne aaye: Khata → unka naam → Collect → amount → drawer mein.'), btn: 'Collect', go: '/admin/khata' },
            { t: T('Send a reminder with the WhatsApp button on their khata.', 'उनके खाते पर WhatsApp बटन से याद दिलाएँ।',
                'Unke khate pe WhatsApp button se yaad dilao.'), btn: 'WhatsApp' },
        ],
        example: T('Example: Mr Sharma takes cigarettes and tea on khata all week (₹640). On Saturday he pays ₹640 cash: Collect → ₹640.',
            'उदाहरण: शर्मा जी पूरे हफ़्ते खाते पर चाय-सिगरेट लेते हैं (₹640)। शनिवार को ₹640 कैश देते हैं: Collect → ₹640।',
            'Example: Sharma ji poore hafte khate pe chai-cigarette lete hain (₹640). Shanivar ko ₹640 cash dete hain: Collect → ₹640.'),
    },
    {
        id: 'club', perms: ['customers.view'], icon: '👑', when: T('Daily, 5 minutes', 'रोज़, 5 मिनट', 'Roz, 5 minute'),
        title: T('Customers: FiKA Club, birthdays, members', 'ग्राहक: FiKA क्लब, जन्मदिन, मेंबर', 'Customers: FiKA Club, birthday, member'),
        intro: T('Keep regulars happy: approve birthday changes, activate members, send rewards.', 'रेगुलर ग्राहकों को खुश रखें: जन्मदिन बदलाव मंज़ूर करें, मेंबर चालू करें, इनाम भेजें।',
            'Regulars ko khush rakho: birthday change approve karo, member activate karo, rewards bhejo.'),
        steps: [
            { t: T('FiKA Club → Requests: someone wants their birthday changed. Ask to see an ID, then Approve or Reject.',
                'FiKA Club → Requests: कोई अपना जन्मदिन बदलवाना चाहता है। ID देखें, फिर Approve या Reject।',
                'FiKA Club → Requests: koi apna birthday badalwana chahta hai. ID dekho, phir Approve ya Reject.'), btn: 'Approve', go: '/admin/club?tab=requests' },
            { t: T('FiKA Club → Members Club: "Wants to join". Take the fee (cash/UPI), tap Paid · Activate.', 'FiKA Club → Members Club: "Wants to join"। फ़ीस लें (कैश/UPI), Paid · Activate दबाएँ।',
                'FiKA Club → Members Club: "Wants to join". Fees lo (cash/UPI), Paid · Activate dabao.'), btn: 'Paid · Activate', go: '/admin/club?tab=members' },
            { t: T('Rewards → WhatsApp to-do: send the ready messages (birthday gifts, milestone coupons).', 'Rewards → WhatsApp to-do: तैयार मैसेज भेजें (जन्मदिन गिफ्ट, माइलस्टोन कूपन)।',
                'Rewards → WhatsApp to-do: ready message bhejo (birthday gift, milestone coupon).'), btn: 'WhatsApp to-do', go: '/admin/rewards?tab=todo' },
            { t: T('Once a week: FiKA Club → Leaderboard → Pick top 10 → Give reward.', 'हफ़्ते में एक बार: FiKA Club → Leaderboard → Pick top 10 → Give reward।',
                'Hafte mein ek baar: FiKA Club → Leaderboard → Pick top 10 → Give reward.'), btn: 'Give reward', go: '/admin/club?tab=leaders' },
        ],
        example: T('Example: Priya reached 60 orders in 12 months and tapped Join. She pays ₹199 by UPI; you tap Paid · Activate. From her next bill she gets 10% off (up to ₹50), once a day.',
            'उदाहरण: प्रिया के 12 महीने में 60 ऑर्डर हो गए और उसने Join दबाया। वह ₹199 UPI से देती है; आप Paid · Activate दबाते हैं। अगले बिल से उसे 10% छूट (₹50 तक), दिन में एक बार।',
            'Example: Priya ke 12 mahine mein 60 order ho gaye, usne Join dabaya. ₹199 UPI se deti hai; aap Paid · Activate dabao. Agle bill se 10% off (₹50 tak), din mein ek baar.'),
    },
    {
        id: 'stock', perms: ['inventory.view'], icon: '📦', when: T('When stock comes or goes', 'जब माल आए या खराब हो', 'Jab maal aaye ya kharab ho'),
        title: T('Stock: purchases and wastage', 'स्टॉक: ख़रीद और बर्बादी', 'Stock: purchase aur wastage'),
        intro: T('Recipes take stock out with every sale. You record what comes in and what is thrown away.',
            'हर बिक्री पर रेसिपी के हिसाब से स्टॉक घटता है। आप आया हुआ माल और फेंका हुआ माल लिखें।',
            'Har bikri pe recipe ke hisaab se stock ghat-ta hai. Aap aaya hua maal aur phenka hua maal likho.'),
        steps: [
            { t: T('Goods arrive: Inventory → Purchases → New purchase → vendor, items, quantity, price, bill photo.', 'माल आया: Inventory → Purchases → New purchase → वेंडर, आइटम, मात्रा, दाम, बिल फ़ोटो।',
                'Maal aaya: Inventory → Purchases → New purchase → vendor, items, quantity, rate, bill photo.'), btn: 'New purchase', go: '/admin/inventory?tab=purchases' },
            { t: T('Something spoiled? Inventory → Stock → the item row → Wastage (minus sign) → quantity.', 'कुछ ख़राब हुआ? Inventory → Stock → आइटम की लाइन → Wastage (माइनस) → मात्रा।',
                'Kuch kharab hua? Inventory → Stock → item ki line → Wastage (minus) → quantity.'), btn: '⊖ Wastage', go: '/admin/inventory' },
            { t: T('Once a week, count the shelf: Counts & leaks → Start. Differences show where stock went missing.', 'हफ़्ते में एक बार गिनती: Counts & leaks → Start। फ़र्क दिखाता है स्टॉक कहाँ गया।',
                'Hafte mein ek baar ginti: Counts & leaks → Start. Fark dikhata hai stock kahan gaya.'), btn: 'Start', go: '/admin/inventory?tab=counts' },
        ],
        example: T('Example: 10 litres of milk arrive for ₹560. New purchase → Milk 10 L → ₹560 → photo of the bill. 1 litre goes sour: Wastage → 1 L.',
            'उदाहरण: 10 लीटर दूध ₹560 में आया। New purchase → Milk 10 L → ₹560 → बिल की फ़ोटो। 1 लीटर फट गया: Wastage → 1 L।',
            'Example: 10 litre doodh ₹560 mein aaya. New purchase → Milk 10 L → ₹560 → bill ki photo. 1 litre phat gaya: Wastage → 1 L.'),
    },
    {
        id: 'close', perms: ['orders.edit'], icon: '🌙', when: T('Every night', 'हर रात', 'Har raat'),
        title: T('Closing the day', 'दिन बंद करना', 'Din band karna'),
        intro: T('Make sure every bill is paid, count the cash, close the shift.', 'पक्का करें हर बिल भरा गया, कैश गिनें, शिफ्ट बंद करें।',
            'Pakka karo har bill bhara gaya, cash gino, shift band karo.'),
        steps: [
            { t: T('Orders: nothing should be left unpaid. Take payment or cancel (with a reason).', 'Orders: कोई बिल बाकी नहीं होना चाहिए। पेमेंट लें या कारण के साथ कैंसल करें।',
                'Orders: koi bill baaki nahi hona chahiye. Payment lo ya reason ke saath cancel karo.'), go: '/admin/orders' },
            { t: T('Add today\'s expenses (vegetables, gas, delivery): Finance → Add expense.', 'आज के ख़र्च जोड़ें (सब्ज़ी, गैस, डिलीवरी): Finance → Add expense।',
                'Aaj ke kharche add karo (sabzi, gas, delivery): Finance → Add expense.'), btn: 'Add expense', go: '/admin/finance' },
            { t: T('Cash & Shifts → Close shift → count the notes → type what you counted. Explain any difference.', 'कैश और शिफ्ट → Close shift → नोट गिनें → गिना हुआ लिखें। फ़र्क हो तो कारण लिखें।',
                'Cash & Shifts → Close shift → note gino → jo gina woh likho. Fark ho toh reason likho.'), btn: 'Close shift', go: '/admin/shifts' },
            { t: T('Only the person who opened the shift, or the manager or owner, can close it and see the cash in the drawer. Others can still record a pay-out.',
                'शिफ्ट वही बंद कर सकता है जिसने खोली थी, या मैनेजर/मालिक; ड्रॉअर का कैश भी वही देखते हैं। बाकी स्टाफ Pay out लिख सकते हैं।',
                'Shift wahi band kar sakta hai jisne kholi thi, ya manager/owner; drawer ka cash bhi wahi dekhte hain. Baaki staff Pay out likh sakte hain.'), go: '/admin/shifts' },
            { t: T('My day → Check out.', 'मेरा दिन → Check out।', 'My day → Check out.'), btn: 'Check out', go: '/admin/me' },
            { t: T('Owner: Reports → Today: sales, cash, UPI, profit.', 'मालिक: Reports → Today: बिक्री, कैश, UPI, मुनाफ़ा।', 'Owner: Reports → Today: bikri, cash, UPI, munafa.'), go: '/admin/reports' },
        ],
        example: T('Example: Expected cash ₹8,450, counted ₹8,400. Write "₹50 change given extra by mistake". The owner gets an alert for differences.',
            'उदाहरण: अपेक्षित कैश ₹8,450, गिना ₹8,400। लिखें "₹50 गलती से ज़्यादा छुट्टा दिया"। फ़र्क होने पर मालिक को अलर्ट जाता है।',
            'Example: Expected cash ₹8,450, gina ₹8,400. Likho "₹50 galti se zyada change diya". Fark hone pe owner ko alert jaata hai.'),
    },
    {
        id: 'weekly', perms: ['reports.view', 'finance.view'], icon: '📅', when: T('Weekly and monthly', 'हफ़्ते और महीने में', 'Hafte aur mahine mein'),
        title: T('Owner checks: staff, salary, profit', 'मालिक की जाँच: स्टाफ, सैलरी, मुनाफ़ा', 'Owner check: staff, salary, munafa'),
        intro: T('Ten minutes a week keeps the money and the team in order.', 'हफ़्ते के दस मिनट से पैसा और टीम ठीक रहते हैं।',
            'Hafte ke das minute se paisa aur team theek rehte hain.'),
        steps: [
            { t: T('Attendance: who was late or absent; approve leave.', 'हाज़िरी: कौन लेट या गैरहाज़िर था; छुट्टी मंज़ूर करें।', 'Haaziri: kaun late ya absent tha; chhutti approve karo.'), go: '/admin/attendance' },
            { t: T('Profit advisor: read the suggestions (raise a price, drop a dish) and accept or skip.', 'मुनाफ़ा सलाहकार: सुझाव पढ़ें (दाम बढ़ाएँ, डिश हटाएँ) और मानें या छोड़ें।',
                'Munafa salah: suggestion padho (rate badhao, dish hatao) aur accept ya skip karo.'), go: '/admin/profit' },
            { t: T('Month end: Payroll → check each slip → pay.', 'महीने के अंत में: Payroll → हर स्लिप देखें → पेमेंट करें।', 'Mahine ke end mein: Payroll → har slip dekho → pay karo.'), go: '/admin/payroll' },
            { t: T('GST: Reports → GST, share with your accountant.', 'GST: Reports → GST, अपने CA को भेजें।', 'GST: Reports → GST, apne CA ko bhejo.'), go: '/admin/reports' },
        ],
        example: T('Example: The advisor says "Cold Coffee costs ₹48 to make and sells for ₹90; raise to ₹110". You accept: the menu price changes.',
            'उदाहरण: सलाहकार कहता है "कोल्ड कॉफ़ी बनाने में ₹48, बिकती ₹90 में; ₹110 करें"। आप मानते हैं: मेन्यू का दाम बदल जाता है।',
            'Example: Advisor bolta hai "Cold Coffee banane mein ₹48, bikti ₹90 mein; ₹110 karo". Accept karo: menu rate badal jaata hai.'),
    },
    {
        id: 'team', perms: ['staff.view'], icon: '👥', when: T('When needed', 'ज़रूरत पर', 'Zaroorat pe'),
        title: T('Staff logins and the phone app', 'स्टाफ लॉगिन और फ़ोन ऐप', 'Staff login aur phone app'),
        intro: T('Every staff member gets their own login and role. Alerts ring on their phone.', 'हर स्टाफ को अपना लॉगिन और रोल मिलता है। अलर्ट उनके फ़ोन पर बजते हैं।',
            'Har staff ko apna login aur role milta hai. Alerts unke phone pe bajte hain.'),
        steps: [
            { t: T('Staff logins & Roles → Add staff → name, mobile, role (Cashier, Kitchen…), PIN.', 'Staff logins & Roles → Add staff → नाम, मोबाइल, रोल (Cashier, Kitchen…), PIN।',
                'Staff logins & Roles → Add staff → naam, mobile, role (Cashier, Kitchen…), PIN.'), btn: 'Add staff', go: '/admin/staff' },
            { t: T('Forgot PIN? Tap the key 🔑 next to their name to reset it.', 'PIN भूल गए? उनके नाम के पास चाबी 🔑 दबाकर रीसेट करें।', 'PIN bhool gaye? Naam ke paas chaabi 🔑 dabake reset karo.'), btn: '🔑' },
            { t: T('On each staff phone: install the app, log in, My day → Turn on alerts on this phone.', 'हर स्टाफ के फ़ोन पर: ऐप इंस्टॉल करें, लॉगिन करें, My day → Turn on alerts on this phone।',
                'Har staff ke phone pe: app install karo, login karo, My day → Turn on alerts on this phone.'), btn: 'Turn on alerts on this phone', go: '/admin/me' },
            { t: T('Someone leaves? Switch their login off in Staff logins (history stays).', 'कोई काम छोड़ दे? Staff logins में उनका लॉगिन बंद करें (रिकॉर्ड रहता है)।',
                'Koi kaam chhod de? Staff logins mein unka login band karo (record rehta hai).') },
        ],
        example: T('Example: New cashier Sonu joins. Add staff → Sonu → 98xxxxxx → Cashier → PIN 4821. He can sell and take payment, but cannot see profit or salaries.',
            'उदाहरण: नया कैशियर सोनू आया। Add staff → सोनू → 98xxxxxx → Cashier → PIN 4821। वह बेच और पैसे ले सकता है, पर मुनाफ़ा या सैलरी नहीं देख सकता।',
            'Example: Naya cashier Sonu aaya. Add staff → Sonu → 98xxxxxx → Cashier → PIN 4821. Woh bech aur paise le sakta hai, par munafa ya salary nahi dekh sakta.'),
    },
];

export const FAQ = [
    { q: T('The alarm shows but makes no sound.', 'अलार्म दिखता है पर आवाज़ नहीं आती।', 'Alarm dikhta hai par awaaz nahi aati.'),
        a: T('Browsers keep sound off until the screen is tapped once after opening the app. Tap anywhere (or the yellow "Tap for alarm sound" button by the bell) and check the volume of the laptop or phone.',
            'ऐप खोलने के बाद स्क्रीन एक बार छूने तक ब्राउज़र आवाज़ बंद रखता है। कहीं भी (या घंटी के पास पीला "Tap for alarm sound" बटन) छुएँ और लैपटॉप या फ़ोन की आवाज़ देखें।',
            'App kholne ke baad screen ek baar chhoone tak browser awaaz band rakhta hai. Kahin bhi (ya ghanti ke paas peela "Tap for alarm sound" button) chhuo aur laptop ya phone ka volume dekho.') },
    { q: T('A staff member cannot check in.', 'स्टाफ चेक-इन नहीं कर पा रहा।', 'Staff check in nahi kar pa raha.'),
        a: T('Three checks: their login is linked to an employee (Setup checklist → Link them now), the cafe location is set (Attendance), and they are standing inside the cafe with location on.',
            'तीन चीज़ें देखें: उनका लॉगिन कर्मचारी से जुड़ा है (Setup checklist → Link them now), कैफ़े की लोकेशन सेट है (Attendance), और वे लोकेशन चालू रखकर कैफ़े के अंदर हैं।',
            'Teen cheezein dekho: unka login employee se juda hai (Setup checklist → Link them now), cafe location set hai (Attendance), aur woh location on rakhke cafe ke andar hain.'), go: '/admin/setup' },
    { q: T('The kiosk says "Your plan allows N kiosks".', 'कियोस्क कहता है "Your plan allows N kiosks"।', 'Kiosk kehta hai "Your plan allows N kiosks".'),
        a: T('All kiosk slots are in use. Settings → Cafe settings → Devices → turn off kiosks you no longer use, then set up the new screen again.',
            'सारे कियोस्क स्लॉट भरे हैं। Settings → Cafe settings → Devices → जो कियोस्क अब नहीं चलते उन्हें बंद करें, फिर नई स्क्रीन दोबारा सेट करें।',
            'Saare kiosk slot bhare hain. Settings → Cafe settings → Devices → jo kiosk ab nahi chalte unhe band karo, phir nayi screen dobara set karo.'), go: '/admin/settings' },
    { q: T('I cannot see a page or a button that my colleague has.', 'मुझे कोई पेज या बटन नहीं दिखता जो साथी को दिखता है।', 'Mujhe koi page ya button nahi dikhta jo saathi ko dikhta hai.'),
        a: T('Each role sees only what it is allowed to. Pages that say "You can look" are view-only for you. Ask the owner to change your role or add an exception in Staff logins & Roles.',
            'हर रोल को वही दिखता है जिसकी अनुमति है। जिन पेजों पर "You can look" लिखा है, वे आपके लिए सिर्फ़ देखने के लिए हैं। मालिक से रोल बदलने या Staff logins & Roles में exception देने को कहें।',
            'Har role ko wahi dikhta hai jiski permission hai. Jin pages pe "You can look" likha hai, woh aapke liye sirf dekhne ke liye hain. Owner se role badalne ya Staff logins & Roles mein exception dene ko bolo.') },
    { q: T('The kitchen shows old tickets from yesterday.', 'किचन में कल के पुराने टिकट दिख रहे हैं।', 'Kitchen mein kal ke purane ticket dikh rahe hain.'),
        a: T('Tickets older than 6 hours move to "From earlier" at the bottom. Open it and tap "Mark these as served" (payments do not change).',
            '6 घंटे से पुराने टिकट नीचे "From earlier" में चले जाते हैं। उसे खोलें और "Mark these as served" दबाएँ (पेमेंट नहीं बदलता)।',
            '6 ghante se purane ticket neeche "From earlier" mein chale jaate hain. Use kholo aur "Mark these as served" dabao (payment nahi badalta).'), go: '/admin/kitchen' },
    { q: T('A customer says their order did not reach the kitchen.', 'ग्राहक कहता है उसका ऑर्डर किचन नहीं पहुँचा।', 'Customer bolta hai order kitchen nahi pahuncha.'),
        a: T('Open Orders. If it says "Confirm table" in yellow, tap Confirm table: the kitchen gets it then. If it is not there at all, ask the customer to show their order screen.',
            'Orders खोलें। अगर पीले में "Confirm table" है तो Confirm table दबाएँ: तब किचन को मिलेगा। अगर दिख ही नहीं रहा, ग्राहक से उसकी ऑर्डर स्क्रीन दिखाने को कहें।',
            'Orders kholo. Peele mein "Confirm table" ho toh Confirm table dabao: tab kitchen ko milega. Dikhe hi nahi, toh customer se order screen dikhane ko bolo.'), go: '/admin/orders' },
    { q: T('Scanning the table QR says "isn\'t in use any more".', 'टेबल का QR स्कैन करने पर "isn\'t in use any more" आता है।', 'Table ka QR scan karne pe "isn\'t in use any more" aata hai.'),
        a: T('That sticker is old or was replaced. Tables → that table → print the QR again and stick it.', 'वह स्टिकर पुराना है या बदल दिया गया। Tables → वह टेबल → QR फिर से प्रिंट करके चिपकाएँ।',
            'Woh sticker purana hai ya badal diya gaya. Tables → woh table → QR dobara print karke chipkao.'), go: '/admin/tables' },
    { q: T('The printer is not printing.', 'प्रिंटर प्रिंट नहीं कर रहा।', 'Printer print nahi kar raha.'),
        a: T('Check paper and power, switch the printer off and on, then press KOT or Print again. Still stuck? Raise a ticket below with a photo.',
            'काग़ज़ और बिजली देखें, प्रिंटर बंद-चालू करें, फिर KOT या Print दोबारा दबाएँ। फिर भी नहीं? नीचे फ़ोटो के साथ टिकट भेजें।',
            'Kaagaz aur bijli dekho, printer band-chalu karo, phir KOT ya Print dobara dabao. Phir bhi nahi? Neeche photo ke saath ticket bhejo.') },
    { q: T('The cash at closing is less or more than expected.', 'बंद करते समय कैश कम या ज़्यादा है।', 'Band karte waqt cash kam ya zyada hai.'),
        a: T('Check Pay out entries (money taken from the drawer) and cash orders paid by UPI by mistake. Write the reason when closing; the owner sees it.',
            'Pay out (ड्रॉअर से निकाले पैसे) और गलती से UPI की जगह कैश लिखे ऑर्डर देखें। बंद करते समय कारण लिखें; मालिक देखेगा।',
            'Pay out (drawer se nikale paise) aur galti se cash/UPI ulta likhe order dekho. Band karte waqt reason likho; owner dekhega.'), go: '/admin/shifts' },
    { q: T('A customer entered the wrong birthday.', 'ग्राहक ने गलत जन्मदिन डाल दिया।', 'Customer ne galat birthday daal diya.'),
        a: T('They tap "Wrong date? Ask the cafe to fix it" on their Rewards page. You approve in FiKA Club → Requests after seeing an ID.',
            'वे अपने Rewards पेज पर "Wrong date? Ask the cafe to fix it" दबाएँ। आप ID देखकर FiKA Club → Requests में मंज़ूर करें।',
            'Woh apne Rewards page pe "Wrong date? Ask the cafe to fix it" dabayein. Aap ID dekhkar FiKA Club → Requests mein approve karo.'), go: '/admin/club?tab=requests' },
    { q: T('A member did not get their discount.', 'मेंबर को छूट नहीं मिली।', 'Member ko discount nahi mila.'),
        a: T('The member discount works on one bill a day, with a cap per bill, and only after their phone number is on the bill. Check the 👑 tag next to their name.',
            'मेंबर छूट दिन में एक बिल पर, एक सीमा तक, और बिल पर उनका नंबर होने पर ही लगती है। उनके नाम के पास 👑 टैग देखें।',
            'Member discount din mein ek bill pe, ek limit tak, aur bill pe unka number hone pe hi lagta hai. Naam ke paas 👑 tag dekho.') },
    { q: T('The pickup TV is not showing a number.', 'पिकअप टीवी पर नंबर नहीं दिख रहा।', 'Pickup TV pe number nahi dikh raha.'),
        a: T('Table orders do not show unless "Include table orders" is on (Pickup screen page). Orders show as ready only when every dish is marked ready.',
            'टेबल के ऑर्डर तभी दिखते हैं जब "Include table orders" चालू हो (Pickup screen पेज)। ऑर्डर तभी तैयार दिखता है जब हर डिश तैयार मार्क हो।',
            'Table ke order tabhi dikhte hain jab "Include table orders" on ho (Pickup screen page). Order ready tabhi dikhta hai jab har dish ready mark ho.'), go: '/admin/pickup-screen' },
    { q: T('A dish shows "out of stock" but we have it.', 'डिश "out of stock" दिखा रही है पर हमारे पास है।', 'Dish "out of stock" dikha rahi hai par hamare paas hai.'),
        a: T('Menu → Items → switch the item on again. If stock is wrong, Inventory → Stock → Correct stock.', 'Menu → Items → आइटम फिर से चालू करें। स्टॉक गलत हो तो Inventory → Stock → Correct stock।',
            'Menu → Items → item dobara on karo. Stock galat ho toh Inventory → Stock → Correct stock.'), go: '/admin/menu' },
    { q: T('The internet went off.', 'इंटरनेट चला गया।', 'Internet chala gaya.'),
        a: T('Keep using the Counter and Kiosk. Orders wait on the device (you will see a yellow "waiting to send" sign) and go up by themselves later. QR ordering by customers needs internet.',
            'काउंटर और कियोस्क चलाते रहें। ऑर्डर डिवाइस में रुकते हैं (पीला "waiting to send" दिखेगा) और बाद में अपने-आप चले जाते हैं। ग्राहकों के QR ऑर्डर के लिए इंटरनेट चाहिए।',
            'Counter aur Kiosk chalate raho. Order device mein rukte hain (peela "waiting to send" dikhega) aur baad mein apne aap chale jaate hain. Customer ke QR order ke liye net chahiye.') },
];

export const UI = {
    title: T('Help & guide', 'मदद और गाइड', 'Help aur guide'),
    sub: T('How to run the cafe day with this app, step by step. Tap a grey button to open that page.',
        'इस ऐप से कैफ़े का पूरा दिन कैसे चलाएँ, कदम-दर-कदम। स्लेटी बटन दबाकर वह पेज खोलें।',
        'Is app se cafe ka poora din kaise chalayein, step by step. Grey button dabake woh page kholo.'),
    guide: T('Guide', 'गाइड', 'Guide'),
    where: T('Where is it?', 'कहाँ मिलेगा?', 'Kahan milega?'),
    daily: T('Every day', 'हर दिन', 'Har din'),
    manage: T('Setting up and running the cafe', 'कैफ़े सेट करना और चलाना', 'Cafe set karna aur chalana'),
    forMe: T('For me', 'मेरे लिए', 'Mere liye'),
    everything: T('Everything', 'सब कुछ', 'Sab kuch'),
    whereSub: T('Type what you want to change; tap Open to go there.', 'जो बदलना है लिखें; वहाँ जाने के लिए Open दबाएँ।', 'Jo badalna hai likho; wahan jaane ke liye Open dabao.'),
    faq: T('Common problems', 'आम समस्याएँ', 'Aam problems'),
    tickets: T('Ask N.A.I.R. / Report a problem', 'N.A.I.R. से पूछें / समस्या बताएँ', 'N.A.I.R. se poocho / problem batao'),
    example: T('Real example', 'असली उदाहरण', 'Asli example'),
    tip: T('Tip', 'सुझाव', 'Tip'),
    open: T('Open', 'खोलें', 'Kholo'),
};
