// The guide, part 2: setting up and running the cafe (owner and manager topics), in English, Hindi and Hinglish.
// Same shape as SOP in sop.js. `perms`: the topic shows under "For me" only for people with one of these.
const T = (en, hi, hg) => ({ en, hi, hg });

export const SOP_MANAGE = [
    {
        id: 'setup', icon: '✅', perms: ['settings.view'], when: T('First week', 'पहला हफ़्ता', 'Pehla hafta'),
        title: T('Setting up a new cafe', 'नया कैफ़े सेट करना', 'Naya cafe set karna'),
        intro: T('The Setup checklist shows every step a new cafe needs, with a tick when it is done.',
            'Setup checklist में नए कैफ़े के सारे कदम हैं; पूरा होते ही टिक लग जाता है।',
            'Setup checklist mein naye cafe ke saare steps hain; poora hote hi tick lag jaata hai.'),
        steps: [
            { t: T('Open Settings → Setup checklist. The bar on top shows how many main steps are done.',
                'Settings → Setup checklist खोलें। ऊपर की पट्टी बताती है कितने मुख्य कदम पूरे हुए।',
                'Settings → Setup checklist kholo. Upar ki patti batati hai kitne main steps poore hue.'), go: '/admin/setup' },
            { t: T('Tap the button next to any step without a tick: it opens the right page.',
                'जिस कदम पर टिक नहीं है उसके बटन को दबाएँ: सही पेज खुल जाएगा।',
                'Jis step pe tick nahi hai uska button dabao: sahi page khul jaayega.') },
            { t: T('Staff not linked to an employee? Tap Link them now. Without it they cannot check in.',
                'स्टाफ कर्मचारी से जुड़े नहीं हैं? Link them now दबाएँ। इसके बिना वे हाज़िरी नहीं लगा सकते।',
                'Staff employee se jude nahi? Link them now dabao. Iske bina woh check in nahi kar sakte.'), btn: 'Link them now' },
            { t: T('"Optional" steps (GST, tables, phone alerts) only matter if your cafe uses them.',
                '"Optional" कदम (GST, टेबल, फ़ोन अलर्ट) तभी ज़रूरी हैं जब कैफ़े उन्हें इस्तेमाल करे।',
                '"Optional" steps (GST, table, phone alert) tabhi zaroori hain jab cafe unhe use kare.') },
            { t: T('Until the main steps are done, the Dashboard shows "Setup: N steps left".',
                'जब तक मुख्य कदम पूरे नहीं होते, Dashboard पर "Setup: N steps left" दिखता है।',
                'Jab tak main steps poore nahi hote, Dashboard pe "Setup: N steps left" dikhta hai.') },
        ],
        example: T('Example: A new cafe opens on Monday. The checklist says 5 of 7. The owner uploads the logo and sets the cafe location: 7 of 7, and the Dashboard reminder goes away.',
            'उदाहरण: नया कैफ़े सोमवार को खुलता है। चेकलिस्ट 5 में से 7 बताती है। मालिक लोगो डालता है और कैफ़े की लोकेशन सेट करता है: 7 में से 7, और Dashboard का रिमाइंडर हट जाता है।',
            'Example: Naya cafe Monday ko khulta hai. Checklist 5 of 7 batati hai. Owner logo daalta hai aur cafe location set karta hai: 7 of 7, aur Dashboard ka reminder hat jaata hai.'),
    },
    {
        id: 'menu', icon: '🍽️', perms: ['menu.view'], when: T('When the menu changes', 'जब मेन्यू बदले', 'Jab menu badle'),
        title: T('Menu: items, prices, categories and tax', 'मेन्यू: आइटम, दाम, श्रेणी और टैक्स', 'Menu: item, daam, category aur tax'),
        intro: T('Everything sold at the counter, kiosk and customer app comes from Menu → Items.',
            'काउंटर, कियोस्क और ग्राहक ऐप पर बिकने वाली हर चीज़ Menu → Items से आती है।',
            'Counter, kiosk aur customer app pe bikne wali har cheez Menu → Items se aati hai.'),
        steps: [
            { t: T('First make categories (Coffee, Snacks…) in Menu → Categories.',
                'पहले Menu → Categories में श्रेणियाँ बनाएँ (Coffee, Snacks…)।',
                'Pehle Menu → Categories mein category banao (Coffee, Snacks…).'), go: '/admin/categories' },
            { t: T('Menu → Items → Add: name, category, price, veg / non-veg, photo. "Sold at" chooses main shop, kiosk or both.',
                'Menu → Items → Add: नाम, श्रेणी, दाम, veg / non-veg, फ़ोटो। "Sold at" से मुख्य दुकान, कियोस्क या दोनों चुनें।',
                'Menu → Items → Add: naam, category, daam, veg / non-veg, photo. "Sold at" se main shop, kiosk ya dono chuno.'), btn: 'Add', go: '/admin/menu' },
            { t: T('Bought-ready products (Coke, chips): choose "Resale product" and tick "Price includes tax" for MRP items.',
                'बना-बनाया सामान (Coke, चिप्स): "Resale product" चुनें और MRP वाले आइटम पर "Price includes tax" टिक करें।',
                'Bana-banaya saamaan (Coke, chips): "Resale product" chuno aur MRP wale item pe "Price includes tax" tick karo.') },
            { t: T('Tax rates live in Menu → Brands & Taxes → Tax groups. The cafe-wide GST is in Settings → Cafe settings.',
                'टैक्स की दरें Menu → Brands & Taxes → Tax groups में हैं। पूरे कैफ़े का GST Settings → Cafe settings में है।',
                'Tax rate Menu → Brands & Taxes → Tax groups mein hai. Poore cafe ka GST Settings → Cafe settings mein hai.'), go: '/admin/catalogue' },
            { t: T('Ran out of a dish? Switch it off in Items: it disappears from every menu until you switch it on.',
                'कोई डिश ख़त्म? Items में उसे बंद करें: जब तक चालू न करें, हर मेन्यू से गायब रहेगी।',
                'Koi dish khatam? Items mein band karo: jab tak on na karo, har menu se gaayab rahegi.') },
            { t: T('Tags New, Bestseller and Recommended show as badges on the customer app.',
                'New, Bestseller और Recommended टैग ग्राहक ऐप पर बैज की तरह दिखते हैं।',
                'New, Bestseller aur Recommended tag customer app pe badge ki tarah dikhte hain.') },
        ],
        example: T('Example: Cold coffee goes from ₹110 to ₹120. Items → Cold Coffee → price 120 → Save. The counter, kiosk and QR menu show ₹120 at once, and the Audit log records who changed it.',
            'उदाहरण: कोल्ड कॉफ़ी ₹110 से ₹120 होती है। Items → Cold Coffee → दाम 120 → Save। काउंटर, कियोस्क और QR मेन्यू तुरंत ₹120 दिखाते हैं, और Audit log में लिखा जाता है किसने बदला।',
            'Example: Cold coffee ₹110 se ₹120 hoti hai. Items → Cold Coffee → daam 120 → Save. Counter, kiosk aur QR menu turant ₹120 dikhate hain, aur Audit log mein likha jaata hai kisne badla.'),
        tip: T('Cashiers and kitchen staff can see the menu but cannot change prices.',
            'कैशियर और किचन स्टाफ मेन्यू देख सकते हैं पर दाम नहीं बदल सकते।',
            'Cashier aur kitchen staff menu dekh sakte hain par daam nahi badal sakte.'),
    },
    {
        id: 'recipes', icon: '🧪', perms: ['inventory.view'], when: T('Once per dish', 'हर डिश पर एक बार', 'Har dish pe ek baar'),
        title: T('Recipes and food cost', 'रेसिपी और खाने की लागत', 'Recipe aur khane ki laagat'),
        intro: T('A recipe tells the app what each dish uses, so stock goes down by itself and you see the real cost and margin.',
            'रेसिपी बताती है हर डिश में क्या लगता है, ताकि स्टॉक अपने-आप घटे और असली लागत व मुनाफ़ा दिखे।',
            'Recipe batati hai har dish mein kya lagta hai, taaki stock apne aap ghate aur asli laagat aur munafa dikhe.'),
        steps: [
            { t: T('Menu → Recipes & Costing → pick a dish marked "Missing recipe".',
                'Menu → Recipes & Costing → "Missing recipe" वाली डिश चुनें।',
                'Menu → Recipes & Costing → "Missing recipe" wali dish chuno.'), go: '/admin/recipes' },
            { t: T('Add each ingredient with quantity and unit (e.g. Milk 200 ml, Coffee 8 g). Add a waste % if some is lost.',
                'हर सामग्री मात्रा और यूनिट के साथ जोड़ें (जैसे दूध 200 ml, कॉफ़ी 8 g)। कुछ बर्बाद होता हो तो Waste % डालें।',
                'Har ingredient quantity aur unit ke saath jodo (jaise doodh 200 ml, coffee 8 g). Kuch barbaad hota ho toh Waste % daalo.') },
            { t: T('The page shows cost per portion, food cost % and margin. Red means food cost above 40%.',
                'पेज हर हिस्से की लागत, food cost % और मुनाफ़ा दिखाता है। लाल का मतलब food cost 40% से ज़्यादा।',
                'Page har portion ki laagat, food cost % aur margin dikhata hai. Laal matlab food cost 40% se zyada.') },
            { t: T('Costs come from your purchase bills in Stock → Inventory → Purchases, so enter every bill.',
                'लागत Stock → Inventory → Purchases के ख़रीद बिलों से आती है, इसलिए हर बिल डालें।',
                'Laagat Stock → Inventory → Purchases ke kharid bill se aati hai, isliye har bill daalo.'), go: '/admin/inventory?tab=purchases' },
        ],
        example: T('Example: Latte sells for ₹150. Recipe: milk 200 ml (₹12) + coffee 8 g (₹14) + cup (₹6) = ₹32 food cost, 21%. Margin ₹118.',
            'उदाहरण: लाटे ₹150 का बिकता है। रेसिपी: दूध 200 ml (₹12) + कॉफ़ी 8 g (₹14) + कप (₹6) = ₹32 लागत, 21%। मुनाफ़ा ₹118।',
            'Example: Latte ₹150 ka bikta hai. Recipe: doodh 200 ml (₹12) + coffee 8 g (₹14) + cup (₹6) = ₹32 laagat, 21%. Margin ₹118.'),
    },
    {
        id: 'tables', icon: '🪑', perms: ['tables.view'], when: T('Once, then when tables change', 'एक बार, फिर टेबल बदलने पर', 'Ek baar, phir table badalne pe'),
        title: T('Tables and table QR codes', 'टेबल और टेबल के QR कोड', 'Table aur table ke QR code'),
        intro: T('Each table gets its own QR. Customers scan it to see the menu and order straight to the kitchen.',
            'हर टेबल का अपना QR होता है। ग्राहक स्कैन करके मेन्यू देखते हैं और सीधे किचन में ऑर्डर करते हैं।',
            'Har table ka apna QR hota hai. Customer scan karke menu dekhte hain aur seedha kitchen mein order karte hain.'),
        steps: [
            { t: T('Sell → Tables → Add Multiple Tables: start and end number, seats → Create Tables.',
                'Sell → Tables → Add Multiple Tables: शुरू और आख़िरी नंबर, सीटें → Create Tables।',
                'Sell → Tables → Add Multiple Tables: start aur end number, seats → Create Tables.'), btn: 'Create Tables', go: '/admin/tables' },
            { t: T('Print the QR codes from Tables and stick one on each table.',
                'Tables से QR कोड प्रिंट करें और हर टेबल पर एक चिपकाएँ।',
                'Tables se QR code print karo aur har table pe ek chipkao.') },
            { t: T('A sticker lost or photographed by someone outside? Re-issue that table QR: the old one stops working.',
                'स्टिकर खो गया या किसी ने बाहर से फ़ोटो ली? उस टेबल का QR दोबारा बनाएँ: पुराना बंद हो जाएगा।',
                'Sticker kho gaya ya kisi ne bahar se photo li? Us table ka QR dobara banao: purana band ho jaayega.') },
            { t: T('Customer app → "Staff confirm a table\'s first order" makes staff tap Confirm table before the kitchen sees a new table\'s first order.',
                'Customer app → "Staff confirm a table\'s first order" चालू करने पर किसी टेबल का पहला ऑर्डर किचन से पहले स्टाफ Confirm table करता है।',
                'Customer app → "Staff confirm a table\'s first order" on karne pe table ka pehla order kitchen se pehle staff Confirm table karta hai.'), go: '/admin/customer-app' },
            { t: T('Customer app → "Staff accept every QR order before the kitchen sees it" (on by default): every QR order rings full screen and reaches the kitchen only after someone taps Accept. Turn it off to send QR orders straight to the kitchen.',
                'Customer app → "Staff accept every QR order before the kitchen sees it" (पहले से चालू): हर QR ऑर्डर पूरी स्क्रीन पर बजता है और Accept दबाने के बाद ही किचन पहुँचता है। बंद करें तो QR ऑर्डर सीधे किचन जाते हैं।',
                'Customer app → "Staff accept every QR order before the kitchen sees it" (pehle se on): har QR order poori screen pe bajta hai aur Accept dabane ke baad hi kitchen pahunchta hai. Band karo toh QR order seedha kitchen jaate hain.'), go: '/admin/customer-app' },
        ],
        example: T('Example: Table 4 orders 2 cappuccinos from the QR. The counter laptop rings a full-screen alarm, the kitchen gets the ticket "T4", and the bill is added to table 4.',
            'उदाहरण: टेबल 4 QR से 2 कैपुचीनो मँगाती है। काउंटर लैपटॉप पर पूरी स्क्रीन का अलार्म बजता है, किचन को "T4" टिकट मिलता है, और बिल टेबल 4 में जुड़ता है।',
            'Example: Table 4 QR se 2 cappuccino mangati hai. Counter laptop pe full-screen alarm bajta hai, kitchen ko "T4" ticket milta hai, aur bill table 4 mein judta hai.'),
    },
    {
        id: 'offers', icon: '🏷️', perms: ['coupons.view', 'rewards.view'], when: T('When you run an offer', 'जब ऑफ़र चलाएँ', 'Jab offer chalao'),
        title: T('Coupons, points and offers', 'कूपन, पॉइंट्स और ऑफ़र', 'Coupon, points aur offer'),
        intro: T('Coupons are codes customers type; points are earned on every bill and spent later.',
            'कूपन वह कोड है जो ग्राहक लिखते हैं; पॉइंट्स हर बिल पर मिलते हैं और बाद में खर्च होते हैं।',
            'Coupon woh code hai jo customer likhte hain; points har bill pe milte hain aur baad mein kharch hote hain.'),
        steps: [
            { t: T('Customers → Coupons → Add Coupon: code, % or ₹ off, minimum order, valid from / until, how many uses.',
                'Customers → Coupons → Add Coupon: कोड, % या ₹ छूट, न्यूनतम ऑर्डर, कब से / कब तक, कितनी बार।',
                'Customers → Coupons → Add Coupon: code, % ya ₹ off, minimum order, kab se / kab tak, kitni baar.'), btn: 'Add Coupon', go: '/admin/coupons' },
            { t: T('A coupon past its last date shows "Expired" and stops working by itself.',
                'आख़िरी तारीख़ निकलने पर कूपन "Expired" दिखाता है और अपने-आप बंद हो जाता है।',
                'Aakhri date nikalne pe coupon "Expired" dikhata hai aur apne aap band ho jaata hai.') },
            { t: T('Customers → Points: how many points per ₹1, minimum order to earn, and how many points make ₹1 off.',
                'Customers → Points: ₹1 पर कितने पॉइंट, कमाने के लिए न्यूनतम ऑर्डर, और कितने पॉइंट = ₹1 छूट।',
                'Customers → Points: ₹1 pe kitne point, kamane ke liye minimum order, aur kitne point = ₹1 off.'), go: '/admin/loyalty' },
            { t: T('Customers → Rewards → Rules: automatic gifts (every 5th coffee free, comeback offer, Instagram selfie).',
                'Customers → Rewards → Rules: अपने-आप मिलने वाले तोहफ़े (हर 5वीं कॉफ़ी मुफ़्त, वापस आने का ऑफ़र, Instagram सेल्फ़ी)।',
                'Customers → Rewards → Rules: apne aap milne wale gift (har 5vi coffee free, wapas aane ka offer, Instagram selfie).'), go: '/admin/rewards' },
        ],
        example: T('Example: Diwali week: coupon DIWALI10, 10% off, minimum ₹300, valid 1–7 Nov, 200 uses. On 8 Nov it shows Expired.',
            'उदाहरण: दिवाली हफ़्ता: कूपन DIWALI10, 10% छूट, न्यूनतम ₹300, 1–7 नवंबर, 200 बार। 8 नवंबर को Expired दिखता है।',
            'Example: Diwali hafta: coupon DIWALI10, 10% off, minimum ₹300, 1–7 Nov, 200 baar. 8 Nov ko Expired dikhta hai.'),
        tip: T('Cashiers can see coupons but cannot add or change them.', 'कैशियर कूपन देख सकते हैं पर जोड़ या बदल नहीं सकते।', 'Cashier coupon dekh sakte hain par add ya change nahi kar sakte.'),
    },
    {
        id: 'customerapp', icon: '📱', perms: ['settings.view'], when: T('Weekly', 'हर हफ़्ते', 'Har hafte'),
        title: T('Customer app: banners, announcements, look', 'ग्राहक ऐप: बैनर, सूचना, रंग-रूप', 'Customer app: banner, announcement, look'),
        intro: T('What customers see when they open your app or scan a table QR.',
            'ग्राहक आपका ऐप खोलने या टेबल QR स्कैन करने पर क्या देखते हैं।',
            'Customer aapka app kholne ya table QR scan karne pe kya dekhte hain.'),
        steps: [
            { t: T('Menu → Customer app → Announcement strip: one line on top (e.g. "Live music Friday 8 pm").',
                'Menu → Customer app → Announcement strip: ऊपर एक लाइन (जैसे "Live music Friday 8 pm")।',
                'Menu → Customer app → Announcement strip: upar ek line (jaise "Live music Friday 8 pm").'), go: '/admin/customer-app' },
            { t: T('Customers can use the app in English, हिन्दी or Hinglish: they pick it on the welcome card or with the language button in the header (a Hindi phone starts in Hindi). Banners and the announcement show as you write them; the bill stays in English.',
                'ग्राहक ऐप English, हिन्दी या Hinglish में चला सकते हैं: स्वागत कार्ड पर या हेडर के भाषा बटन से चुनते हैं (हिन्दी फ़ोन पर ऐप हिन्दी में खुलता है)। बैनर और सूचना वैसी दिखती हैं जैसी आप लिखते हैं; बिल English में रहता है।',
                'Customer app English, हिन्दी ya Hinglish mein chala sakte hain: welcome card pe ya header ke bhasha button se chunte hain (Hindi phone pe app Hindi mein khulta hai). Banner aur announcement waise dikhte hain jaise aap likhte ho; bill English mein rehta hai.'), go: '/admin/customer-app' },
            { t: T('Menu → Items → open a dish → "Name in Hindi" (optional): customers using Hindi see it small under the dish name.',
                'Menu → Items → डिश खोलें → "Name in Hindi" (वैकल्पिक): हिन्दी वाले ग्राहकों को यह डिश के नाम के नीचे छोटे अक्षरों में दिखता है।',
                'Menu → Items → dish kholo → "Name in Hindi" (optional): Hindi wale customers ko yeh dish ke naam ke neeche chhota dikhta hai.'), go: '/admin/menu' },
            { t: T('Add banner: title, picture, and what it opens (a dish, a category, the rewards page). Set start and end dates.',
                'Add banner: शीर्षक, तस्वीर, और क्या खुले (कोई डिश, श्रेणी, रिवॉर्ड पेज)। शुरू और ख़त्म की तारीख़ डालें।',
                'Add banner: title, photo, aur kya khule (koi dish, category, rewards page). Start aur end date daalo.'), btn: 'Add banner' },
            { t: T('Menu → Homepage Sections: groups of dishes on the home screen (e.g. "Monsoon specials").',
                'Menu → Homepage Sections: होम स्क्रीन पर डिशों के समूह (जैसे "Monsoon specials")।',
                'Menu → Homepage Sections: home screen pe dishes ke group (jaise "Monsoon specials").'), go: '/admin/collections' },
            { t: T('Colours, logo, font and whether the app opens light or dark: Settings → Brand & look.',
                'रंग, लोगो, फ़ॉन्ट और ऐप लाइट खुले या डार्क: Settings → Brand & look।',
                'Rang, logo, font aur app light khule ya dark: Settings → Brand & look.'), go: '/admin/brand' },
        ],
        example: T('Example: Every Tuesday, a "Dosa Tuesday · ₹20 off" banner that opens the Dosa category, from 7 am to 4 pm.',
            'उदाहरण: हर मंगलवार, "Dosa Tuesday · ₹20 off" बैनर जो Dosa श्रेणी खोलता है, सुबह 7 से शाम 4 तक।',
            'Example: Har Tuesday, "Dosa Tuesday · ₹20 off" banner jo Dosa category kholta hai, subah 7 se shaam 4 tak.'),
    },
    {
        id: 'brand', icon: '🎨', perms: ['settings.view'], when: T('Once', 'एक बार', 'Ek baar'),
        title: T('Brand & look: name, logo, colours', 'Brand & look: नाम, लोगो, रंग', 'Brand & look: naam, logo, rang'),
        intro: T('Set once, used everywhere: customer app, staff app, bills, Kiosk and the pickup TV.',
            'एक बार सेट करें, हर जगह इस्तेमाल: ग्राहक ऐप, स्टाफ ऐप, बिल, कियोस्क और पिकअप टीवी।',
            'Ek baar set karo, har jagah use: customer app, staff app, bill, Kiosk aur pickup TV.'),
        steps: [
            { t: T('Settings → Brand & look → Change logo (a square picture works best), cafe name, short line, address, phone, hours.',
                'Settings → Brand & look → Change logo (चौकोर तस्वीर सबसे अच्छी), कैफ़े का नाम, छोटी लाइन, पता, फ़ोन, समय।',
                'Settings → Brand & look → Change logo (square photo best), cafe naam, chhoti line, pata, phone, time.'), btn: 'Change logo', go: '/admin/brand' },
            { t: T('Colours: pick a ready set or your own. A colour too pale to read is blocked; tap "Use a deeper shade".',
                'रंग: तैयार सेट या अपना चुनें। बहुत हल्का रंग जो पढ़ा न जाए, रुक जाता है; "Use a deeper shade" दबाएँ।',
                'Rang: ready set ya apna chuno. Bahut halka rang jo padha na jaaye, ruk jaata hai; "Use a deeper shade" dabao.') },
            { t: T('Corners (round, soft, square) and font (Poppins, Mukta, Baloo 2, Hind: all read Hindi well).',
                'कोने (गोल, नरम, चौकोर) और फ़ॉन्ट (Poppins, Mukta, Baloo 2, Hind: सब हिंदी अच्छी पढ़ते हैं)।',
                'Kone (round, soft, square) aur font (Poppins, Mukta, Baloo 2, Hind: sab Hindi achhi padhte hain).') },
            { t: T('"Customer app opens in": the customer\'s phone setting, always light or always dark.',
                '"Customer app opens in": ग्राहक के फ़ोन की सेटिंग, हमेशा लाइट या हमेशा डार्क।',
                '"Customer app opens in": customer ke phone ki setting, hamesha light ya hamesha dark.') },
            { t: T('Save for the whole cafe. Phones and the TV pick it up the next time they open or refresh.',
                'Save for the whole cafe दबाएँ। फ़ोन और टीवी अगली बार खुलने या रिफ्रेश होने पर नया रूप दिखाते हैं।',
                'Save for the whole cafe dabao. Phone aur TV agli baar khulne ya refresh hone pe naya look dikhate hain.'), btn: 'Save for the whole cafe' },
        ],
        example: T('Example: Chai Adda picks the Teal set, Round corners and Mukta. The bill prints the logo in grey at the top.',
            'उदाहरण: चाय अड्डा Teal सेट, Round कोने और Mukta चुनता है। बिल पर ऊपर लोगो स्लेटी रंग में छपता है।',
            'Example: Chai Adda Teal set, Round corners aur Mukta chunta hai. Bill pe upar logo grey mein chhapta hai.'),
    },
    {
        id: 'finance', icon: '💰', perms: ['finance.view'], when: T('Daily and monthly', 'रोज़ और हर महीने', 'Roz aur har mahine'),
        title: T('Expenses, bills to pay and the money ledger', 'ख़र्चे, चुकाने वाले बिल और पैसों का हिसाब', 'Kharche, chukane wale bill aur paison ka hisaab'),
        intro: T('Every rupee in and out, by account: counter drawer, kiosk drawer, office safe, bank, UPI and card.',
            'हर रुपया अंदर और बाहर, खाते के हिसाब से: काउंटर ड्रॉअर, कियोस्क ड्रॉअर, ऑफ़िस तिजोरी, बैंक, UPI और कार्ड।',
            'Har rupaya andar aur bahar, account ke hisaab se: counter drawer, kiosk drawer, office safe, bank, UPI aur card.'),
        steps: [
            { t: T('Money → Finance → Expenses → Add expense: amount, category, paid from which account, photo of the bill.',
                'Money → Finance → Expenses → Add expense: रक़म, श्रेणी, किस खाते से दिया, बिल की फ़ोटो।',
                'Money → Finance → Expenses → Add expense: amount, category, kis account se diya, bill ki photo.'), btn: 'Add expense', go: '/admin/finance?tab=expenses' },
            { t: T('Payables: vendor bills not yet paid and monthly bills (rent, internet) that appear on their day each month.',
                'Payables: वेंडर के बकाया बिल और हर महीने के बिल (किराया, इंटरनेट) जो अपनी तारीख़ पर आ जाते हैं।',
                'Payables: vendor ke baaki bill aur har mahine ke bill (kiraya, internet) jo apni date pe aa jaate hain.'), go: '/admin/finance?tab=payables' },
            { t: T('Money ledger: every movement with who did it. Use it when the cash does not match.',
                'Money ledger: हर लेन-देन, किसने किया के साथ। कैश न मिले तो यही देखें।',
                'Money ledger: har len-den, kisne kiya ke saath. Cash na mile toh yahi dekho.'), go: '/admin/finance?tab=ledger' },
            { t: T('Shifts show counted cash vs expected for each drawer, with the reason for any difference.',
                'Shifts में हर ड्रॉअर का गिना हुआ कैश बनाम अपेक्षित दिखता है, अंतर के कारण के साथ।',
                'Shifts mein har drawer ka gina hua cash vs expected dikhta hai, antar ke reason ke saath.') },
        ],
        example: T('Example: The milkman is paid ₹1,800 from the counter drawer. Add expense → Milk → ₹1,800 → Cash – Counter drawer. At closing, the expected cash is already ₹1,800 lower.',
            'उदाहरण: दूधवाले को काउंटर ड्रॉअर से ₹1,800 दिए। Add expense → Milk → ₹1,800 → Cash – Counter drawer। बंद करते समय अपेक्षित कैश पहले से ₹1,800 कम होता है।',
            'Example: Doodhwale ko counter drawer se ₹1,800 diye. Add expense → Milk → ₹1,800 → Cash – Counter drawer. Band karte waqt expected cash pehle se ₹1,800 kam hota hai.'),
    },
    {
        id: 'reports', icon: '📊', perms: ['finance.view', 'reports.view'], when: T('Weekly and monthly', 'हर हफ़्ते और महीने', 'Har hafte aur mahine'),
        title: T('Reports, GST and the Profit advisor', 'रिपोर्ट, GST और मुनाफ़ा सलाहकार', 'Report, GST aur Profit advisor'),
        intro: T('How the cafe is really doing, what to send the CA, and what to change to earn more.',
            'कैफ़े असल में कैसा चल रहा है, CA को क्या भेजें, और ज़्यादा कमाने के लिए क्या बदलें।',
            'Cafe asal mein kaisa chal raha hai, CA ko kya bhejo, aur zyada kamane ke liye kya badlo.'),
        steps: [
            { t: T('Money → Reports → Profit & loss: sales, food cost, expenses and profit for any period.',
                'Money → Reports → Profit & loss: किसी भी समय के बिक्री, खाने की लागत, ख़र्च और मुनाफ़ा।',
                'Money → Reports → Profit & loss: kisi bhi period ki bikri, food cost, kharch aur munafa.'), go: '/admin/reports' },
            { t: T('GST tab: sales by GST rate and Downloads for the CA (one file per month).',
                'GST टैब: GST दर के हिसाब से बिक्री और CA के लिए डाउनलोड (हर महीने की एक फ़ाइल)।',
                'GST tab: GST rate ke hisaab se bikri aur CA ke liye Downloads (har mahine ki ek file).') },
            { t: T('Profit target: set a weekly or monthly profit target and see how close this week and month are.',
                'Profit target: हफ़्ते या महीने का मुनाफ़ा लक्ष्य रखें और देखें यह हफ़्ता और महीना कितना पास है।',
                'Profit target: hafte ya mahine ka munafa target rakho aur dekho yeh hafta aur mahina kitna paas hai.') },
            { t: T('Sales trends: revenue by day, top dishes and customers. The gear on Estimated profit sets your usual margin.',
                'Sales trends: रोज़ की कमाई, टॉप डिश और ग्राहक। Estimated profit पर गियर से अपना आम मुनाफ़ा % रखें।',
                'Sales trends: roz ki kamai, top dish aur customer. Estimated profit pe gear se apna aam margin rakho.'), go: '/admin/analytics' },
            { t: T('Profit advisor → Suggestions: plain advice (raise this price, push that dish), each with the numbers behind it. Mark done or Dismiss.',
                'Profit advisor → Suggestions: सीधी सलाह (यह दाम बढ़ाएँ, वह डिश बेचें), पीछे के आँकड़ों के साथ। Mark done या Dismiss।',
                'Profit advisor → Suggestions: seedhi salah (yeh daam badhao, woh dish becho), peeche ke numbers ke saath. Mark done ya Dismiss.'), go: '/admin/profit' },
            { t: T('Swiggy / Zomato import: upload their statement to see the real profit on delivery orders.',
                'Swiggy / Zomato import: उनका स्टेटमेंट डालें और डिलीवरी ऑर्डर का असली मुनाफ़ा देखें।',
                'Swiggy / Zomato import: unka statement daalo aur delivery order ka asli munafa dekho.'), go: '/admin/profit?tab=import' },
        ],
        example: T('Example: The advisor says "Masala chai: food cost 18%, sells 60 a day. Raising ₹20 → ₹25 adds about ₹9,000 a month." The owner changes the price and taps Mark done; Decisions & results shows the effect a month later.',
            'उदाहरण: सलाहकार कहता है "मसाला चाय: लागत 18%, रोज़ 60 बिकती है। ₹20 → ₹25 करने से लगभग ₹9,000 महीना बढ़ेगा।" मालिक दाम बदलता है और Mark done दबाता है; Decisions & results महीने बाद असर दिखाता है।',
            'Example: Advisor kehta hai "Masala chai: laagat 18%, roz 60 bikti hai. ₹20 → ₹25 karne se lagbhag ₹9,000 mahina badhega." Owner daam badalta hai aur Mark done dabata hai; Decisions & results mahine baad asar dikhata hai.'),
    },
    {
        id: 'attendance', icon: '🕘', perms: ['employees.view'], when: T('Every day', 'हर दिन', 'Har din'),
        title: T('Attendance and check-in', 'हाज़िरी और चेक-इन', 'Haaziri aur check-in'),
        intro: T('Staff check in from their own phone with a selfie, only when they are inside the cafe.',
            'स्टाफ अपने फ़ोन से सेल्फ़ी के साथ चेक-इन करते हैं, सिर्फ़ कैफ़े के अंदर रहते हुए।',
            'Staff apne phone se selfie ke saath check in karte hain, sirf cafe ke andar rehte hue.'),
        steps: [
            { t: T('Once: stand inside the cafe, Team → Attendance → Cafe location → Use my location → Save. Until then a yellow warning shows.',
                'एक बार: कैफ़े के अंदर खड़े होकर Team → Attendance → Cafe location → Use my location → Save। तब तक पीली चेतावनी दिखती है।',
                'Ek baar: cafe ke andar khade hoke Team → Attendance → Cafe location → Use my location → Save. Tab tak peeli warning dikhti hai.'), btn: 'Use my location', go: '/admin/attendance#cafe-location' },
            { t: T('Each login must be linked to an employee (new logins are linked automatically). See the App login column.',
                'हर लॉगिन किसी कर्मचारी से जुड़ा होना चाहिए (नए लॉगिन अपने-आप जुड़ते हैं)। App login कॉलम देखें।',
                'Har login kisi employee se juda hona chahiye (naye login apne aap judte hain). App login column dekho.') },
            { t: T('The board shows who is in, late, on a break or outside the cafe, with selfies.',
                'बोर्ड पर दिखता है कौन अंदर है, लेट है, ब्रेक पर है या कैफ़े से बाहर, सेल्फ़ी के साथ।',
                'Board pe dikhta hai kaun andar hai, late hai, break pe hai ya cafe se bahar, selfie ke saath.') },
            { t: T('Someone leaves the cafe during their shift: the owner gets an alarm after the set minutes.',
                'शिफ्ट के दौरान कोई कैफ़े से निकले: तय मिनट बाद मालिक को अलार्म मिलता है।',
                'Shift ke beech koi cafe se nikle: tay minute baad owner ko alarm milta hai.') },
        ],
        example: T('Example: Ravi\'s shift starts at 9:00. He checks in at 9:18 with a selfie: past the 10 grace minutes, so the board shows him 18 min late.',
            'उदाहरण: रवि की शिफ्ट 9:00 बजे है। वह 9:18 पर सेल्फ़ी के साथ चेक-इन करता है: 10 मिनट की छूट निकल गई, इसलिए बोर्ड उसे 18 मिनट लेट दिखाता है।',
            'Example: Ravi ki shift 9:00 baje hai. Woh 9:18 pe selfie ke saath check in karta hai: 10 minute ki chhoot nikal gayi, isliye board use 18 minute late dikhata hai.'),
    },
    {
        id: 'payroll', icon: '🧾', perms: ['employees.view'], when: T('Every month', 'हर महीने', 'Har mahine'),
        title: T('Payroll, leave and advances', 'वेतन, छुट्टी और एडवांस', 'Tankhwah, chhutti aur advance'),
        intro: T('Monthly pay is worked out from attendance, leave, overtime, advances and penalties.',
            'महीने का वेतन हाज़िरी, छुट्टी, ओवरटाइम, एडवांस और जुर्माने से बनता है।',
            'Mahine ki tankhwah haaziri, chhutti, overtime, advance aur penalty se banti hai.'),
        steps: [
            { t: T('Team → Employees: set each person\'s pay (monthly, daily or hourly), shift hours and weekly off.',
                'Team → Employees: हर व्यक्ति का वेतन (महीना, रोज़ या घंटा), शिफ्ट के घंटे और साप्ताहिक छुट्टी डालें।',
                'Team → Employees: har vyakti ki pay (monthly, daily ya hourly), shift hours aur weekly off daalo.'), go: '/admin/employees' },
            { t: T('Payroll → Leave: add and approve leave. Advances & penalties: Give advance, Add penalty.',
                'Payroll → Leave: छुट्टी जोड़ें और मंज़ूर करें। Advances & penalties: Give advance, Add penalty।',
                'Payroll → Leave: chhutti jodo aur approve karo. Advances & penalties: Give advance, Add penalty.'), go: '/admin/payroll?tab=leave' },
            { t: T('Payroll tab (owner, or roles with "See salaries"): check payable days and net pay, then Finalize.',
                'Payroll टैब (मालिक, या "See salaries" वाले रोल): देय दिन और कुल वेतन जाँचें, फिर Finalize।',
                'Payroll tab (owner, ya "See salaries" wale role): payable days aur net pay check karo, phir Finalize.'), btn: 'Finalize', go: '/admin/payroll' },
            { t: T('Pay, choosing the account the money comes from. Print the payslip for the employee to sign.',
                'Pay दबाएँ, किस खाते से पैसा जाए चुनें। कर्मचारी के हस्ताक्षर के लिए payslip प्रिंट करें।',
                'Pay dabao, kis account se paisa jaaye chuno. Employee ke sign ke liye payslip print karo.'), btn: 'Pay' },
        ],
        example: T('Example: Sonu earns ₹12,000 a month, took a ₹2,000 advance and 1 unpaid leave. Net pay ₹9,600. Paid from the office safe, payslip printed.',
            'उदाहरण: सोनू का वेतन ₹12,000 महीना, ₹2,000 एडवांस लिया और 1 बिना वेतन छुट्टी। कुल ₹9,600। ऑफ़िस तिजोरी से दिया, payslip प्रिंट।',
            'Example: Sonu ki tankhwah ₹12,000 mahina, ₹2,000 advance liya aur 1 bina pay ki chhutti. Net ₹9,600. Office safe se diya, payslip print.'),
        tip: T('Managers without "See salaries" do not see the Payroll tab; leave and advances still work for them.',
            '"See salaries" के बिना मैनेजर को Payroll टैब नहीं दिखता; छुट्टी और एडवांस फिर भी चलते हैं।',
            '"See salaries" ke bina manager ko Payroll tab nahi dikhta; chhutti aur advance phir bhi chalte hain.'),
    },
    {
        id: 'roles', icon: '🔐', perms: ['staff.view'], when: T('When someone joins', 'जब कोई जुड़े', 'Jab koi jude'),
        title: T('Roles and permissions: who can do what', 'रोल और अनुमतियाँ: कौन क्या कर सकता है', 'Role aur permission: kaun kya kar sakta hai'),
        intro: T('Every login has a role. The role decides which pages they see and what they can change.',
            'हर लॉगिन का एक रोल है। रोल तय करता है वे कौन से पेज देखें और क्या बदल सकें।',
            'Har login ka ek role hai. Role tay karta hai woh kaun se page dekhein aur kya badal sakein.'),
        steps: [
            { t: T('Team → Staff logins & Roles → Roles & permissions: a grid of sections (Menu, Orders…) and actions (view, add, edit, delete).',
                'Team → Staff logins & Roles → Roles & permissions: सेक्शन (Menu, Orders…) और काम (देखना, जोड़ना, बदलना, हटाना) की तालिका।',
                'Team → Staff logins & Roles → Roles & permissions: section (Menu, Orders…) aur kaam (view, add, edit, delete) ki table.'), go: '/admin/staff' },
            { t: T('Orders "add" is front-of-house work: taking money, accepting QR orders, cancelling, moving tables and the cash drawer. Orders "edit" alone (the Chef) only moves dishes along: started, ready, served.',
                'Orders का "add" काउंटर/सर्विस का काम है: पैसे लेना, QR ऑर्डर स्वीकार करना, रद्द करना, टेबल बदलना और कैश ड्रॉअर। सिर्फ़ Orders "edit" (शेफ़) डिश को आगे बढ़ाता है: शुरू, तैयार, परोसा।',
                'Orders ka "add" counter/service ka kaam hai: paise lena, QR order accept karna, cancel karna, table badalna aur cash drawer. Sirf Orders "edit" (Chef) dish ko aage badhata hai: shuru, ready, served.'), go: '/admin/staff' },
            { t: T('"Opens on" picks the page a role sees after login: Waiter opens on Orders, Chef on Kitchen. Change it for any role.',
                '"Opens on" से तय होता है कि लॉगिन के बाद कौन सा पेज खुले: Waiter के लिए Orders, Chef के लिए Kitchen। किसी भी रोल के लिए बदल सकते हैं।',
                '"Opens on" se tay hota hai login ke baad kaunsa page khule: Waiter ke liye Orders, Chef ke liye Kitchen. Kisi bhi role ke liye badal sakte ho.'), go: '/admin/staff' },
            { t: T('Sensitive rights are separate: see salaries, see profit and cost, give discounts, void bills, see full customer phone numbers.',
                'संवेदनशील अधिकार अलग हैं: वेतन देखना, मुनाफ़ा और लागत देखना, छूट देना, बिल रद्द करना, ग्राहक का पूरा नंबर देखना।',
                'Sensitive rights alag hain: salary dekhna, munafa aur laagat dekhna, discount dena, bill void karna, customer ka poora number dekhna.') },
            { t: T('One person needs one extra right? Use Exceptions (the sliders icon next to their name) instead of a new role.',
                'किसी एक को एक अधिकार ज़्यादा चाहिए? नया रोल बनाने के बजाय Exceptions (नाम के पास स्लाइडर आइकन) इस्तेमाल करें।',
                'Kisi ek ko ek right zyada chahiye? Naya role banane ki jagah Exceptions (naam ke paas slider icon) use karo.') },
            { t: T('Pages someone can only look at say "You can look" and hide the change buttons.',
                'जिन पेजों को कोई सिर्फ़ देख सकता है, वहाँ "You can look" लिखा होता है और बदलने के बटन छिपे रहते हैं।',
                'Jin pages ko koi sirf dekh sakta hai, wahan "You can look" likha hota hai aur badalne ke button chhupe rehte hain.') },
        ],
        example: T('Example: Head cashier Kabir needs to give discounts above the normal limit. Exceptions → Give discounts → Allow. Other cashiers stay as they are.',
            'उदाहरण: हेड कैशियर कबीर को सामान्य सीमा से ज़्यादा छूट देनी है। Exceptions → Give discounts → Allow। बाकी कैशियर वैसे ही रहते हैं।',
            'Example: Head cashier Kabir ko normal limit se zyada discount dena hai. Exceptions → Give discounts → Allow. Baaki cashier waise hi rehte hain.'),
    },
    {
        id: 'alerts', icon: '🔔', when: T('Once per person', 'हर व्यक्ति के लिए एक बार', 'Har vyakti ke liye ek baar'),
        title: T('Alerts, the full-screen alarm and sound', 'अलर्ट, पूरी स्क्रीन का अलार्म और आवाज़', 'Alert, full-screen alarm aur awaaz'),
        intro: T('New QR orders, payment requests and staff leaving the cafe can take over the whole screen with a sound until someone taps Acknowledge.',
            'नए QR ऑर्डर, पेमेंट माँग और स्टाफ का कैफ़े छोड़ना पूरी स्क्रीन पर आवाज़ के साथ दिखते हैं, जब तक कोई Acknowledge न दबाए।',
            'Naye QR order, payment request aur staff ka cafe chhodna poori screen pe awaaz ke saath dikhte hain, jab tak koi Acknowledge na dabaye.'),
        steps: [
            { t: T('After opening the app, tap the screen once. Browsers keep sound off until then; a yellow "Tap for alarm sound" button shows by the bell.',
                'ऐप खोलने के बाद स्क्रीन एक बार छुएँ। तब तक ब्राउज़र आवाज़ बंद रखता है; घंटी के पास पीला "Tap for alarm sound" बटन दिखता है।',
                'App kholne ke baad screen ek baar chhuo. Tab tak browser awaaz band rakhta hai; ghanti ke paas peela "Tap for alarm sound" button dikhta hai.'), btn: 'Tap for alarm sound' },
            { t: T('A new table order fills the screen with the dishes, total and waiting time: tap Accept (a first order on a table goes to the kitchen at that moment). A bill or UPI request comes in blue: tap Take payment. Several at once stack as chips. Busy? Snooze 5 or 10 min.',
                'नया टेबल ऑर्डर पूरी स्क्रीन पर डिश, कुल और इंतज़ार के समय के साथ आता है: Accept दबाएँ (टेबल का पहला ऑर्डर तभी किचन जाता है)। बिल या UPI की माँग नीले रंग में आती है: Take payment दबाएँ। कई एक साथ आएँ तो चिप बनकर रुकते हैं। व्यस्त? 5 या 10 मिनट Snooze।',
                'Naya table order poori screen pe dish, total aur wait time ke saath aata hai: Accept dabao (table ka pehla order tabhi kitchen jaata hai). Bill ya UPI request neele rang mein aati hai: Take payment dabao. Kai ek saath aayein toh chips ban ke rukte hain. Busy? 5 ya 10 min Snooze.'), btn: 'Accept' },
            { t: T('Nobody answers for 5 minutes? The alert flashes faster, rings louder and the owner gets an alert. A screen that should stay calm (kitchen TV): bell → untick “Full-screen order alerts on this screen”.',
                '5 मिनट तक कोई जवाब न दे? अलर्ट तेज़ चमकता है, ज़ोर से बजता है और मालिक को अलर्ट जाता है। जो स्क्रीन शांत रहे (किचन टीवी): घंटी → “Full-screen order alerts on this screen” हटाएँ।',
                '5 min tak koi jawab na de? Alert tez chamakta hai, zor se bajta hai aur owner ko alert jaata hai. Jo screen shaant rahe (kitchen TV): ghanti → “Full-screen order alerts on this screen” untick karo.') },
            { t: T('Owner: Settings → Alerts sets, per person, Alarm (full screen), Loud, Normal or Off for each kind of alert, and quiet hours.',
                'मालिक: Settings → Alerts में हर व्यक्ति के लिए हर तरह के अलर्ट को Alarm (पूरी स्क्रीन), Loud, Normal या Off, और शांत समय सेट करें।',
                'Owner: Settings → Alerts mein har vyakti ke liye har alert ko Alarm (full screen), Loud, Normal ya Off, aur quiet hours set karo.'), go: '/admin/alerts' },
            { t: T('Phone alerts when the app is closed: My day → Turn on alerts on this phone.',
                'ऐप बंद हो तब भी फ़ोन पर अलर्ट: My day → Turn on alerts on this phone।',
                'App band ho tab bhi phone pe alert: My day → Turn on alerts on this phone.'), btn: 'Turn on alerts on this phone', go: '/admin/me' },
        ],
        example: T('Example: The counter laptop is in full screen on the Kitchen. Table 6 orders by QR: the screen turns red with a sound. Kabir taps Acknowledge and the order opens.',
            'उदाहरण: काउंटर लैपटॉप किचन पर पूरी स्क्रीन में है। टेबल 6 QR से ऑर्डर करती है: स्क्रीन आवाज़ के साथ लाल हो जाती है। कबीर Acknowledge दबाता है और ऑर्डर खुलता है।',
            'Example: Counter laptop Kitchen pe full screen mein hai. Table 6 QR se order karti hai: screen awaaz ke saath laal ho jaati hai. Kabir Acknowledge dabata hai aur order khulta hai.'),
        tip: T('Quiet hours turn alerts down, but new orders and payment requests still ring.',
            'शांत समय में अलर्ट धीमे हो जाते हैं, पर नए ऑर्डर और पेमेंट माँग फिर भी बजते हैं।',
            'Quiet hours mein alert dheeme ho jaate hain, par naye order aur payment request phir bhi bajte hain.'),
    },
    {
        id: 'screens', icon: '🖥️', perms: ['orders.view'], when: T('Once per screen', 'हर स्क्रीन पर एक बार', 'Har screen pe ek baar'),
        title: T('Screens: kitchen TV, kiosk, pickup TV and devices', 'स्क्रीन: किचन टीवी, कियोस्क, पिकअप टीवी और डिवाइस', 'Screen: kitchen TV, kiosk, pickup TV aur device'),
        intro: T('Each counter, kiosk and kitchen screen gets a short code (C1, K1, D1). The owner can see and turn them off.',
            'हर काउंटर, कियोस्क और किचन स्क्रीन को एक छोटा कोड मिलता है (C1, K1, D1)। मालिक उन्हें देख और बंद कर सकता है।',
            'Har counter, kiosk aur kitchen screen ko ek chhota code milta hai (C1, K1, D1). Owner unhe dekh aur band kar sakta hai.'),
        steps: [
            { t: T('Kitchen TV or tablet: open Kitchen → Full screen. Only tickets show, no menu. Tickets older than 6 hours fold into "From earlier".',
                'किचन टीवी या टैबलेट: Kitchen → Full screen खोलें। सिर्फ़ टिकट दिखते हैं। 6 घंटे से पुराने टिकट "From earlier" में चले जाते हैं।',
                'Kitchen TV ya tablet: Kitchen → Full screen kholo. Sirf ticket dikhte hain. 6 ghante se purane ticket "From earlier" mein chale jaate hain.'), btn: 'Full screen', go: '/admin/kitchen' },
            { t: T('Self-order kiosk: open Sell → Kiosk on that screen and tap "Set up this screen as a kiosk". It uses one kiosk slot of your plan.',
                'सेल्फ़-ऑर्डर कियोस्क: उस स्क्रीन पर Sell → Kiosk खोलें और "Set up this screen as a kiosk" दबाएँ। इसमें प्लान का एक कियोस्क स्लॉट लगता है।',
                'Self-order kiosk: us screen pe Sell → Kiosk kholo aur "Set up this screen as a kiosk" dabao. Isme plan ka ek kiosk slot lagta hai.'), btn: 'Set up this screen as a kiosk', go: '/admin/kiosk' },
            { t: T('Pickup TV: Sell → Pickup screen → add a screen, then open its link on the TV; ready token numbers show there.',
                'पिकअप टीवी: Sell → Pickup screen → स्क्रीन जोड़ें, फिर उसका लिंक टीवी पर खोलें; तैयार टोकन नंबर वहाँ दिखते हैं।',
                'Pickup TV: Sell → Pickup screen → screen add karo, phir uska link TV pe kholo; ready token number wahan dikhte hain.'), go: '/admin/pickup-screen' },
            { t: T('Settings → Cafe settings → Devices: every screen with when it was last used. Turn off old ones to free kiosk slots.',
                'Settings → Cafe settings → Devices: हर स्क्रीन, आख़िरी बार कब इस्तेमाल हुई। कियोस्क स्लॉट ख़ाली करने के लिए पुरानी बंद करें।',
                'Settings → Cafe settings → Devices: har screen, aakhri baar kab use hui. Kiosk slot khaali karne ke liye purani band karo.'), btn: 'Turn off', go: '/admin/settings' },
        ],
        example: T('Example: The old kiosk tablet broke. Devices → K2 "Last used 40 days ago" → Turn off. The new tablet sets itself up as K3.',
            'उदाहरण: पुराना कियोस्क टैबलेट ख़राब हो गया। Devices → K2 "Last used 40 days ago" → Turn off। नया टैबलेट K3 बनकर सेट हो जाता है।',
            'Example: Purana kiosk tablet kharab ho gaya. Devices → K2 "Last used 40 days ago" → Turn off. Naya tablet K3 bankar set ho jaata hai.'),
    },
    {
        id: 'myscreen', icon: '🌗', when: T('Any time', 'कभी भी', 'Kabhi bhi'),
        title: T('Your screen: language, light or dark', 'आपकी स्क्रीन: भाषा, लाइट या डार्क', 'Aapki screen: bhasha, light ya dark'),
        intro: T('Each person chooses for their own phone or laptop; it does not change anyone else\'s screen.',
            'हर व्यक्ति अपने फ़ोन या लैपटॉप के लिए चुनता है; किसी और की स्क्रीन नहीं बदलती।',
            'Har vyakti apne phone ya laptop ke liye chunta hai; kisi aur ki screen nahi badalti.'),
        steps: [
            { t: T('The sun / moon button at the top switches light and dark in one tap.',
                'ऊपर का सूरज / चाँद बटन एक टैप में लाइट और डार्क बदलता है।',
                'Upar ka suraj / chaand button ek tap mein light aur dark badalta hai.') },
            { t: T('Laptop: the side menu has English / हिन्दी / Hinglish and Auto / Light / Dark. Phone: More → Language and Screen colours.',
                'लैपटॉप: साइड मेन्यू में English / हिन्दी / Hinglish और Auto / Light / Dark। फ़ोन: More → Language और Screen colours।',
                'Laptop: side menu mein English / हिन्दी / Hinglish aur Auto / Light / Dark. Phone: More → Language aur Screen colours.'), go: '/admin/more' },
            { t: T('The Kitchen has its own light / dark button; the Kiosk always stays light for customers.',
                'किचन का अपना लाइट / डार्क बटन है; कियोस्क ग्राहकों के लिए हमेशा लाइट रहता है।',
                'Kitchen ka apna light / dark button hai; Kiosk customers ke liye hamesha light rehta hai.') },
        ],
    },
];
