// Texts for the small ⓘ buttons next to settings: what it does, an example, who can change it, and the guide topic.
// English, Hindi, Hinglish. Keep them short: they open in a small card (laptop) or a bottom sheet (phone).
const T = (en, hi, hg) => ({ en, hi, hg });
const OWNER = T('Owner', 'मालिक', 'Owner');
const OWNER_MGR = T('Owner, Manager', 'मालिक, मैनेजर', 'Owner, Manager');
const MENU_EDIT = T('Owner, Manager (Menu: edit)', 'मालिक, मैनेजर (Menu: edit)', 'Owner, Manager (Menu: edit)');

export const TIPS = {
    // Settings → Cafe settings
    fssai: { guide: 'setup', who: OWNER_MGR,
        t: T('FSSAI licence number', 'FSSAI लाइसेंस नंबर', 'FSSAI licence number'),
        d: T('Your 14-digit food licence number. It prints on every bill.', 'आपका 14 अंकों का फ़ूड लाइसेंस नंबर। हर बिल पर छपता है।', 'Aapka 14 digit ka food licence number. Har bill pe chhapta hai.'),
        ex: T('“FSSAI: 12345678901234” under the cafe name on the bill.', 'बिल पर कैफ़े के नाम के नीचे “FSSAI: 12345678901234”।', 'Bill pe cafe ke naam ke neeche “FSSAI: 12345678901234”.') },
    service_charge: { guide: 'setup', who: OWNER_MGR,
        t: T('Service charge', 'सर्विस चार्ज', 'Service charge'),
        d: T('An extra % on table and QR bills only. It shows as optional; staff remove it if the customer asks. 0 = off.', 'सिर्फ़ टेबल और QR बिल पर अतिरिक्त %। यह वैकल्पिक दिखता है; ग्राहक कहे तो स्टाफ हटा देता है। 0 = बंद।', 'Sirf table aur QR bill pe extra %. Yeh optional dikhta hai; customer kahe toh staff hata deta hai. 0 = band.'),
        ex: T('5% on a ₹400 table bill adds ₹20. Takeaway and kiosk bills never get it.', '₹400 के टेबल बिल पर 5% = ₹20 और। टेकअवे और कियोस्क बिल पर कभी नहीं।', '₹400 ke table bill pe 5% = ₹20 aur. Takeaway aur kiosk bill pe kabhi nahi.') },
    round_off: { guide: 'setup', who: OWNER_MGR,
        t: T('Round bill totals', 'बिल राउंड ऑफ़', 'Bill round off'),
        d: T('Rounds the total to the nearest rupee so no coins are needed. The difference shows as a separate line on the bill.', 'कुल को नज़दीकी रुपये तक करता है ताकि सिक्के न लगें। अंतर बिल पर अलग लाइन में दिखता है।', 'Total ko nazdeeki rupaye tak karta hai taaki sikke na lagein. Antar bill pe alag line mein dikhta hai.'),
        ex: T('₹157.50 becomes ₹158; ₹157.40 becomes ₹157.', '₹157.50 बनता है ₹158; ₹157.40 बनता है ₹157।', '₹157.50 banta hai ₹158; ₹157.40 banta hai ₹157.') },
    bill_footer: { guide: 'brand', who: OWNER_MGR,
        t: T('Bill footer', 'बिल के नीचे की लाइन', 'Bill footer'),
        d: T('One line printed at the bottom of every bill.', 'हर बिल के सबसे नीचे छपने वाली एक लाइन।', 'Har bill ke sabse neeche chhapne wali ek line.'),
        ex: T('“Thank you! Free Wi-Fi: FIKA-GUEST”.', '“धन्यवाद! फ़्री Wi-Fi: FIKA-GUEST”।', '“Thank you! Free Wi-Fi: FIKA-GUEST”.') },
    shift_tolerance: { guide: 'finance', who: OWNER_MGR,
        t: T('Cash difference allowed', 'कैश में कितना अंतर चलेगा', 'Cash mein kitna antar chalega'),
        d: T('At shift close, a difference bigger than this between counted and expected cash needs a reason and alerts the owner.', 'शिफ्ट बंद करते समय गिने और अपेक्षित कैश में इससे बड़ा अंतर हो तो कारण लिखना पड़ता है और मालिक को अलर्ट जाता है।', 'Shift band karte waqt gine aur expected cash mein isse bada antar ho toh reason likhna padta hai aur owner ko alert jaata hai.'),
        ex: T('Allowed ₹50: short by ₹30 closes normally; short by ₹200 asks for a reason.', 'छूट ₹50: ₹30 कम हो तो सामान्य बंद; ₹200 कम हो तो कारण पूछेगा।', 'Chhoot ₹50: ₹30 kam ho toh normal band; ₹200 kam ho toh reason poochega.') },
    gstin: { guide: 'setup', who: OWNER_MGR,
        t: T('GSTIN', 'GSTIN', 'GSTIN'),
        d: T('Your 15-character GST number, printed at the top of every bill. Leave it empty if the cafe is not GST registered.', 'आपका 15 अक्षर का GST नंबर, हर बिल के ऊपर छपता है। कैफ़े GST में रजिस्टर्ड नहीं है तो ख़ाली छोड़ें।', 'Aapka 15 character ka GST number, har bill ke upar chhapta hai. Cafe GST mein registered nahi hai toh khaali chhodo.'),
        ex: T('22ABCDE1234F1Z5 shows as “GSTIN: 22ABCDE1234F1Z5”.', '22ABCDE1234F1Z5 बिल पर “GSTIN: 22ABCDE1234F1Z5” दिखता है।', '22ABCDE1234F1Z5 bill pe “GSTIN: 22ABCDE1234F1Z5” dikhta hai.') },
    tax_config: { guide: 'menu', who: OWNER_MGR,
        t: T('Taxes on the bill', 'बिल पर टैक्स', 'Bill pe tax'),
        d: T('The taxes added to every item that has no tax group of its own. Changes apply to new orders only.', 'हर उस आइटम पर लगने वाले टैक्स जिसका अपना टैक्स ग्रुप नहीं है। बदलाव सिर्फ़ नए ऑर्डर पर लगते हैं।', 'Har us item pe lagne wale tax jiska apna tax group nahi hai. Badlav sirf naye order pe lagte hain.'),
        ex: T('GST 5%: Latte ₹150 → ₹157.50 on the bill.', 'GST 5%: लाटे ₹150 → बिल पर ₹157.50।', 'GST 5%: Latte ₹150 → bill pe ₹157.50.') },
    // Team → Attendance
    geofence: { guide: 'attendance', who: OWNER,
        t: T('Cafe location and radius', 'कैफ़े की लोकेशन और दायरा', 'Cafe location aur radius'),
        d: T('Staff can check in only within this distance of the cafe. Set it standing inside the cafe. 50–100 m suits most cafes; too small and weak GPS fails.', 'स्टाफ कैफ़े से इतनी दूरी के अंदर ही चेक-इन कर सकता है। कैफ़े के अंदर खड़े होकर सेट करें। ज़्यादातर के लिए 50–100 m; बहुत कम हो तो कमज़ोर GPS फ़ेल।', 'Staff cafe se itni doori ke andar hi check in kar sakta hai. Cafe ke andar khade hoke set karo. Zyadatar ke liye 50–100 m; bahut kam ho toh kamzor GPS fail.'),
        ex: T('75 m: check-in from the counter (12 m) works; from across the road (140 m) does not.', '75 m: काउंटर से (12 m) चेक-इन होगा; सड़क पार से (140 m) नहीं।', '75 m: counter se (12 m) check in hoga; sadak paar se (140 m) nahi.') },
    leave_grace: { guide: 'attendance', who: OWNER,
        t: T('Alert after outside', 'बाहर रहने पर अलर्ट', 'Bahar rehne pe alert'),
        d: T('If someone checked in is outside the cafe for longer than this, the owner gets an alarm. A break pauses it.', 'चेक-इन किया व्यक्ति इससे ज़्यादा देर कैफ़े से बाहर रहे तो मालिक को अलार्म। ब्रेक में नहीं गिना जाता।', 'Check in kiya vyakti isse zyada der cafe se bahar rahe toh owner ko alarm. Break mein nahi gina jaata.'),
        ex: T('10 min: Sonu goes to the bank for 25 min without a break → alarm at 10 min.', '10 मिनट: सोनू बिना ब्रेक 25 मिनट बैंक गया → 10 मिनट पर अलार्म।', '10 min: Sonu bina break 25 min bank gaya → 10 min pe alarm.') },
    ping: { guide: 'attendance', who: OWNER,
        t: T('Check location every', 'हर कितने मिनट लोकेशन', 'Har kitne minute location'),
        d: T('How often a checked-in phone reports where it is. Smaller = quicker alerts but more battery. At least 5 minutes.', 'चेक-इन फ़ोन कितनी बार अपनी जगह बताए। कम = जल्दी अलर्ट पर ज़्यादा बैटरी। कम से कम 5 मिनट।', 'Check in phone kitni baar apni jagah bataye. Kam = jaldi alert par zyada battery. Kam se kam 5 minute.'),
        ex: T('10 min suits most cafes.', 'ज़्यादातर कैफ़े के लिए 10 मिनट ठीक।', 'Zyadatar cafe ke liye 10 min theek.') },
    app_login: { guide: 'attendance', who: OWNER_MGR,
        t: T('App login', 'ऐप लॉगिन', 'App login'),
        d: T('Which staff login belongs to this employee. Without it they cannot check in. New logins are linked automatically.', 'कौन सा स्टाफ लॉगिन इस कर्मचारी का है। इसके बिना चेक-इन नहीं। नए लॉगिन अपने-आप जुड़ते हैं।', 'Kaun sa staff login is employee ka hai. Iske bina check in nahi. Naye login apne aap judte hain.'),
        ex: T('Employee “Ravi Kumar” ↔ login “Ravi · 98xxxxxx21”.', 'कर्मचारी “रवि कुमार” ↔ लॉगिन “रवि · 98xxxxxx21”।', 'Employee “Ravi Kumar” ↔ login “Ravi · 98xxxxxx21”.') },
    // Team → Employees
    pay_type: { guide: 'payroll', who: OWNER_MGR,
        t: T('Pay type', 'वेतन का तरीका', 'Pay type'),
        d: T('Monthly: salary × payable days ÷ days in month (weekly offs, holidays and paid leave count). Daily: daily wage × days worked. Hourly: rate × hours worked.', 'मासिक: वेतन × देय दिन ÷ महीने के दिन (साप्ताहिक छुट्टी, त्योहार और सवेतन छुट्टी गिनी जाती है)। दैनिक: रोज़ की मज़दूरी × काम के दिन। घंटे: दर × काम के घंटे।', 'Monthly: salary × payable days ÷ mahine ke din (weekly off, holiday aur paid leave gine jaate hain). Daily: roz ki mazdoori × kaam ke din. Hourly: rate × kaam ke ghante.'),
        ex: T('₹12,000 monthly, 1 unpaid leave in a 30-day month → ₹11,600.', '₹12,000 मासिक, 30 दिन के महीने में 1 बिना वेतन छुट्टी → ₹11,600।', '₹12,000 monthly, 30 din ke mahine mein 1 unpaid leave → ₹11,600.') },
    ot_rate: { guide: 'payroll', who: OWNER_MGR,
        t: T('Overtime ₹ per hour', 'ओवरटाइम ₹ प्रति घंटा', 'Overtime ₹ per ghanta'),
        d: T('Paid for every hour worked beyond the shift hours on a day. 0 = no overtime pay.', 'शिफ्ट के घंटों से ज़्यादा हर घंटे का भुगतान। 0 = ओवरटाइम नहीं।', 'Shift ke ghanton se zyada har ghante ka bhugtan. 0 = overtime nahi.'),
        ex: T('Shift 9 h, worked 11 h, OT ₹60 → ₹120 extra that day.', 'शिफ्ट 9 घंटे, काम 11 घंटे, OT ₹60 → उस दिन ₹120 और।', 'Shift 9 ghante, kaam 11 ghante, OT ₹60 → us din ₹120 aur.') },
    shift_hours: { guide: 'payroll', who: OWNER_MGR,
        t: T('Shift hours per day', 'रोज़ की शिफ्ट के घंटे', 'Roz ki shift ke ghante'),
        d: T('A normal working day for this person. Hours beyond it count as overtime.', 'इस व्यक्ति का सामान्य कामकाजी दिन। इससे ज़्यादा घंटे ओवरटाइम गिने जाते हैं।', 'Is vyakti ka normal kaam ka din. Isse zyada ghante overtime gine jaate hain.'),
        ex: T('9 hours: 9 am to 6 pm.', '9 घंटे: सुबह 9 से शाम 6।', '9 ghante: subah 9 se shaam 6.') },
    weekly_off: { guide: 'payroll', who: OWNER_MGR,
        t: T('Weekly off', 'साप्ताहिक छुट्टी', 'Weekly off'),
        d: T('The paid day off each week for monthly staff. It is not counted as absent.', 'मासिक स्टाफ की हर हफ़्ते की सवेतन छुट्टी। इसे गैरहाज़िर नहीं गिना जाता।', 'Monthly staff ki har hafte ki paid chhutti. Ise absent nahi gina jaata.'),
        ex: T('Tuesday off: four or five Tuesdays a month are paid.', 'मंगलवार छुट्टी: महीने के 4–5 मंगलवार का वेतन मिलता है।', 'Tuesday off: mahine ke 4–5 Tuesday ka pay milta hai.') },
    // Menu → Items
    item_type: { guide: 'menu', who: MENU_EDIT,
        t: T('Item type', 'आइटम का प्रकार', 'Item type'),
        d: T('Prepared dish: made in the kitchen from a recipe. Resale product: bought ready (Coke, chips), stock counted as pieces. Combo: several items at one price.', 'बनी डिश: रेसिपी से किचन में बनती है। रीसेल: बना-बनाया ख़रीदा (Coke, चिप्स), स्टॉक पीस में। कॉम्बो: कई आइटम एक दाम में।', 'Prepared dish: recipe se kitchen mein banti hai. Resale: bana-banaya kharida (Coke, chips), stock piece mein. Combo: kai item ek daam mein.'),
        ex: T('Masala dosa = Prepared dish; Coke 300 ml = Resale product.', 'मसाला डोसा = Prepared dish; Coke 300 ml = Resale product।', 'Masala dosa = Prepared dish; Coke 300 ml = Resale product.') },
    tax_group: { guide: 'menu', who: MENU_EDIT,
        t: T('Tax group', 'टैक्स ग्रुप', 'Tax group'),
        d: T('Use a different tax for this item. “Cafe default” uses the taxes in Cafe settings.', 'इस आइटम पर अलग टैक्स। “Cafe default” से Cafe settings वाले टैक्स लगते हैं।', 'Is item pe alag tax. “Cafe default” se Cafe settings wale tax lagte hain.'),
        ex: T('Packaged water at 18% while food stays at 5%.', 'पैक्ड पानी 18% पर, खाना 5% पर ही।', 'Packed paani 18% pe, khana 5% pe hi.') },
    pickup_colors: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Pickup card colours', 'पिकअप कार्ड के रंग', 'Pickup card ke rang'),
        d: T('The big Q1 / T5 card on the customer phone: one colour while the order is made, one when it is ready. Empty = the standard look.', 'ग्राहक के फ़ोन पर बड़ा Q1 / T5 कार्ड: ऑर्डर बनते समय एक रंग, तैयार होने पर दूसरा। ख़ाली = सामान्य रंग।', 'Customer ke phone pe bada Q1 / T5 card: order bante waqt ek rang, ready hone pe doosra. Khaali = standard rang.'),
        ex: T('Ready in your brand teal instead of green.', 'तैयार होने पर हरे की जगह आपके ब्रांड का रंग।', 'Ready hone pe hare ki jagah aapke brand ka rang.') },
    pay_options: { guide: 'customerapp', who: OWNER_MGR,
        t: T('How customers pay', 'ग्राहक कैसे पेमेंट करें', 'Customer kaise payment karein'),
        d: T('Switch each way on or off and write its button words. At least one stays on. Empty words = the standard ones in the customer language.', 'हर तरीका चालू या बंद करें और उसके बटन के शब्द लिखें। कम से कम एक चालू रहता है। ख़ाली = ग्राहक की भाषा में सामान्य शब्द।', 'Har tareeka on ya off karo aur uske button ke shabd likho. Kam se kam ek on rehta hai. Khaali = customer ki bhasha mein standard shabd.'),
        ex: T('No UPI QR at the tables: switch "UPI at the table" off.', 'टेबल पर UPI QR नहीं: "UPI at the table" बंद करें।', 'Table pe UPI QR nahi: "UPI at the table" off karo.') },
    points_cash: { guide: 'offers', who: OWNER_MGR,
        t: T('Points as cash', 'पॉइंट को पैसे की तरह', 'Points as cash'),
        d: T('Off: customers spend points only on the Deals you create. On: they can also turn points into money off, using the three rules below. One way per order.', 'बंद: ग्राहक पॉइंट सिर्फ़ आपकी बनाई डील पर खर्च करते हैं। चालू: नीचे के तीन नियमों से पॉइंट को छूट में भी बदल सकते हैं। एक ऑर्डर पर एक ही तरीका।', 'Off: customer points sirf aapki banayi Deals pe kharch karte hain. On: neeche ke teen rules se points ko chhoot mein bhi badal sakte hain. Ek order pe ek hi tareeka.'),
        ex: T('10 points for ₹1, min 100, up to 50% of the bill: 520 points on a ₹300 bill = ₹52 off.', '₹1 के लिए 10 पॉइंट, कम से कम 100, बिल का 50% तक: ₹300 के बिल पर 520 पॉइंट = ₹52 छूट।', '₹1 ke liye 10 points, min 100, bill ka 50% tak: ₹300 ke bill pe 520 points = ₹52 off.') },
    name_hi: { guide: 'menu', who: MENU_EDIT,
        t: T('Name in Hindi', 'हिन्दी में नाम', 'Hindi mein naam'),
        d: T('Optional. Customers who use the app in Hindi see it small under the dish name. The bill keeps the main name.', 'वैकल्पिक। जो ग्राहक ऐप हिन्दी में चलाते हैं, उन्हें यह डिश के नाम के नीचे छोटे अक्षरों में दिखता है। बिल पर मुख्य नाम ही रहता है।', 'Optional. Jo customer app Hindi mein chalate hain, unhe yeh dish ke naam ke neeche chhota dikhta hai. Bill pe main naam hi rehta hai.'),
        ex: T('Masala Dosa → मसाला डोसा', 'Masala Dosa → मसाला डोसा', 'Masala Dosa → मसाला डोसा') },
    hsn: { guide: 'menu', who: MENU_EDIT,
        t: T('HSN code', 'HSN कोड', 'HSN code'),
        d: T('Only for packaged goods sold under their own GST code. Leave blank for cafe food (it uses the restaurant SAC code).', 'सिर्फ़ अपने GST कोड वाले पैक्ड सामान के लिए। कैफ़े के खाने के लिए ख़ाली छोड़ें (रेस्टोरेंट SAC कोड लगता है)।', 'Sirf apne GST code wale packed saamaan ke liye. Cafe ke khane ke liye khaali chhodo (restaurant SAC code lagta hai).'),
        ex: T('Bottled water 2201; latte: blank.', 'बोतल पानी 2201; लाटे: ख़ाली।', 'Bottle paani 2201; latte: khaali.') },
    price_incl_tax: { guide: 'menu', who: MENU_EDIT,
        t: T('Price includes tax', 'दाम में टैक्स शामिल', 'Daam mein tax shaamil'),
        d: T('Tick for MRP items: the customer pays the printed price and the tax is worked out inside it, not added on top.', 'MRP वाले आइटम के लिए टिक करें: ग्राहक छपा दाम ही देता है, टैक्स उसके अंदर गिना जाता है, ऊपर नहीं जुड़ता।', 'MRP wale item ke liye tick karo: customer chhapa daam hi deta hai, tax uske andar gina jaata hai, upar nahi judta.'),
        ex: T('Coke MRP ₹40: the bill shows ₹40, not ₹40 + tax.', 'Coke MRP ₹40: बिल पर ₹40, ₹40 + टैक्स नहीं।', 'Coke MRP ₹40: bill pe ₹40, ₹40 + tax nahi.') },
    restricted: { guide: 'menu', who: MENU_EDIT,
        t: T('Restricted item', 'प्रतिबंधित आइटम', 'Restricted item'),
        d: T('For tobacco and similar: no coupons, rewards or promotions apply to it, and the kiosk reminds staff to check ID.', 'तंबाकू जैसे सामान के लिए: इस पर कूपन, रिवॉर्ड या प्रमोशन नहीं लगते, और कियोस्क स्टाफ को ID जाँचने की याद दिलाता है।', 'Tambaku jaise saamaan ke liye: is pe coupon, reward ya promotion nahi lagte, aur kiosk staff ko ID check karne ki yaad dilata hai.'),
        ex: T('Cigarettes: a 10% coupon on the bill skips them.', 'सिगरेट: बिल पर 10% कूपन उन पर नहीं लगता।', 'Cigarette: bill pe 10% coupon un pe nahi lagta.') },
    sold_at: { guide: 'menu', who: MENU_EDIT,
        t: T('Sold at', 'कहाँ बिकता है', 'Kahan bikta hai'),
        d: T('Main shop = counter and the customer app (QR). Kiosk = the self-order screen. At least one must stay on.', 'मुख्य दुकान = काउंटर और ग्राहक ऐप (QR)। कियोस्क = सेल्फ़-ऑर्डर स्क्रीन। कम से कम एक चालू रहना चाहिए।', 'Main shop = counter aur customer app (QR). Kiosk = self-order screen. Kam se kam ek on rehna chahiye.'),
        ex: T('Cigarettes: kiosk only. Dosa: main shop only.', 'सिगरेट: सिर्फ़ कियोस्क। डोसा: सिर्फ़ मुख्य दुकान।', 'Cigarette: sirf kiosk. Dosa: sirf main shop.') },
    pack_units: { guide: 'menu', who: MENU_EDIT,
        t: T('Pack units', 'पैक यूनिट', 'Pack unit'),
        d: T('Sell the same item in packs with their own price; stock goes down by the pack size.', 'एक ही आइटम को पैक में अलग दाम पर बेचें; स्टॉक पैक के हिसाब से घटता है।', 'Ek hi item ko pack mein alag daam pe becho; stock pack ke hisaab se ghatta hai.'),
        ex: T('Cigarette: 1 piece ₹20, pack of 10 ₹190.', 'सिगरेट: 1 पीस ₹20, 10 का पैक ₹190।', 'Cigarette: 1 piece ₹20, 10 ka pack ₹190.') },
    upsell: { guide: 'menu', who: MENU_EDIT,
        t: T('Cart suggestion', 'कार्ट में सुझाव', 'Cart mein suggestion'),
        d: T('The customer app suggests this item in the cart (“Add a cookie?”).', 'ग्राहक ऐप कार्ट में यह आइटम सुझाता है (“कुकी जोड़ें?”)।', 'Customer app cart mein yeh item suggest karta hai (“Cookie add karein?”).'),
        ex: T('Choco-chip cookie ₹40 shown under every coffee order.', 'हर कॉफ़ी ऑर्डर के नीचे चोको-चिप कुकी ₹40 दिखती है।', 'Har coffee order ke neeche choco-chip cookie ₹40 dikhti hai.') },
    sizes: { guide: 'menu', who: MENU_EDIT,
        t: T('Sizes', 'साइज़', 'Size'),
        d: T('Small, Medium, Large, each with its own full price and an amount like 350 ml. The default size is picked first and is what the counter sells when nobody picks; the dish price follows it.', 'छोटा, मीडियम, बड़ा: हर साइज़ का अपना पूरा दाम और मात्रा (जैसे 350 ml)। डिफ़ॉल्ट साइज़ पहले से चुना रहता है और कोई न चुने तो काउंटर वही बेचता है; डिश का दाम उसी से चलता है।', 'Small, Medium, Large: har size ka apna poora daam aur amount (jaise 350 ml). Default size pehle se chuna rehta hai aur koi na chune toh counter wahi bechta hai; dish ka daam usi se chalta hai.'),
        ex: T('Cold coffee: 250 ml ₹190, 350 ml ₹220 (default), 450 ml ₹260.', 'कोल्ड कॉफ़ी: 250 ml ₹190, 350 ml ₹220 (डिफ़ॉल्ट), 450 ml ₹260।', 'Cold coffee: 250 ml ₹190, 350 ml ₹220 (default), 450 ml ₹260.') },
    choices: { guide: 'menu', who: MENU_EDIT,
        t: T('Choice groups', 'विकल्प के ग्रुप', 'Choice groups'),
        d: T('Questions shared by many dishes: Milk, Sugar, Ice, Flavour. "Pick one" always has an answer (the default); "Pick many" are add-ons with a limit. Extra prices are added to the dish.', 'कई डिशों के साझा सवाल: दूध, चीनी, बर्फ़, फ़्लेवर। "Pick one" में हमेशा एक जवाब (डिफ़ॉल्ट); "Pick many" ऐड-ऑन हैं, सीमा के साथ। अतिरिक्त दाम डिश में जुड़ता है।', 'Kai dishes ke shared sawaal: Milk, Sugar, Ice, Flavour. "Pick one" mein hamesha ek jawab (default); "Pick many" add-on hain, limit ke saath. Extra daam dish mein judta hai.'),
        ex: T('Latte ₹180 + Oat milk +₹40 + Hazelnut +₹30 = ₹250. The kitchen ticket reads "Oat, Hazelnut".', 'लाटे ₹180 + ओट दूध +₹40 + हेज़लनट +₹30 = ₹250। किचन टिकट पर "Oat, Hazelnut"।', 'Latte ₹180 + Oat milk +₹40 + Hazelnut +₹30 = ₹250. Kitchen ticket pe "Oat, Hazelnut".') },
    combos: { guide: 'menu', who: MENU_EDIT,
        t: T('Combos', 'कॉम्बो', 'Combo'),
        d: T('One price for one pick from each part (a drink + a bite). A dish can cost a little extra inside the combo. Set days and hours; outside them the combo is hidden.', 'हर हिस्से से एक चीज़ (एक ड्रिंक + एक स्नैक) का एक दाम। कॉम्बो में कोई डिश थोड़ी ज़्यादा की हो सकती है। दिन और समय चुनें; उसके बाहर कॉम्बो छिपा रहता है।', 'Har part se ek cheez (ek drink + ek snack) ka ek daam. Combo mein koi dish thodi extra ki ho sakti hai. Din aur time chuno; uske bahar combo chhupa rehta hai.'),
        ex: T('"Coffee + bite" ₹249, Mon–Fri 3–6 PM: any coffee with a croissant or cookie; cold brew +₹30.', '"Coffee + bite" ₹249, सोम–शुक्र 3–6 बजे: कोई भी कॉफ़ी के साथ क्रोसां या कुकी; कोल्ड ब्रू +₹30।', '"Coffee + bite" ₹249, Mon–Fri 3–6 PM: koi bhi coffee ke saath croissant ya cookie; cold brew +₹30.') },
    goes_well: { guide: 'menu', who: MENU_EDIT,
        t: T('Goes well with', 'इसके साथ अच्छा लगे', 'Iske saath accha lage'),
        d: T('Up to 8 dishes shown on this dish page, so customers add a bite with one tap.', 'इस डिश के पेज पर 8 तक डिशें, ताकि ग्राहक एक टैप में साथ में कुछ जोड़ ले।', 'Is dish ke page pe 8 tak dishes, taaki customer ek tap mein saath mein kuch add kar le.'),
        ex: T('Cappuccino → Butter croissant, Choco-chip cookie.', 'कैपुचीनो → बटर क्रोसां, चोको-चिप कुकी।', 'Cappuccino → Butter croissant, Choco-chip cookie.') },
    details_page: { guide: 'menu', who: MENU_EDIT,
        t: T('Details page', 'डिश का पेज', 'Dish ka page'),
        d: T('Facts for the customer dish page (calories, caffeine, allergens, ingredients) and ticks for what the page shows. Empty facts are hidden.', 'ग्राहक के डिश पेज के लिए जानकारी (कैलोरी, कैफ़ीन, एलर्जी, सामग्री) और पेज पर क्या दिखे उसके टिक। ख़ाली जानकारी छिपी रहती है।', 'Customer ke dish page ke liye jaankari (calories, caffeine, allergens, ingredients) aur page pe kya dikhe uske tick. Khaali jaankari chhupi rehti hai.'),
        ex: T('Iced latte: 210 kcal, 150 mg caffeine, Milk. Untick "Points earned" to keep it short.', 'आइस्ड लाटे: 210 kcal, 150 mg कैफ़ीन, दूध। छोटा रखने के लिए "Points earned" का टिक हटाएँ।', 'Iced latte: 210 kcal, 150 mg caffeine, Milk. Chhota rakhne ke liye "Points earned" ka tick hatao.') },
    dish_art: { guide: 'menu', who: MENU_EDIT,
        t: T('Drawn picture', 'बनी हुई तस्वीर', 'Bani hui picture'),
        d: T('Shown when the dish has no photo. Automatic guesses from the dish name; pick one if the guess is wrong. A real photo always wins.', 'जब डिश की फ़ोटो न हो तब दिखती है। Automatic डिश के नाम से अंदाज़ा लगाता है; गलत हो तो ख़ुद चुनें। असली फ़ोटो हमेशा पहले।', 'Jab dish ki photo na ho tab dikhti hai. Automatic dish ke naam se andaaza lagata hai; galat ho toh khud chuno. Asli photo hamesha pehle.'),
        ex: T('"Hazelnut Frappe" → Frappe glass with cream.', '"Hazelnut Frappe" → क्रीम वाला फ़्रैपे गिलास।', '"Hazelnut Frappe" → cream wala frappe glass.') },
    // Customers → Points
    points_per_rupee: { guide: 'offers', who: OWNER_MGR,
        t: T('Points per ₹1 spent', '₹1 पर पॉइंट', '₹1 pe point'),
        d: T('Points a customer earns on each bill, counted on the bill amount and rounded down.', 'ग्राहक हर बिल पर कितने पॉइंट कमाता है, बिल की रक़म पर, नीचे की तरफ़ पूरा।', 'Customer har bill pe kitne point kamata hai, bill amount pe, neeche ki taraf poora.'),
        ex: T('1 point per ₹1: a ₹249 bill earns 249 points.', '₹1 पर 1 पॉइंट: ₹249 के बिल पर 249 पॉइंट।', '₹1 pe 1 point: ₹249 ke bill pe 249 point.') },
    points_min_order: { guide: 'offers', who: OWNER_MGR,
        t: T('Minimum order for points', 'पॉइंट के लिए न्यूनतम ऑर्डर', 'Point ke liye minimum order'),
        d: T('Bills below this earn no points.', 'इससे कम के बिल पर पॉइंट नहीं।', 'Isse kam ke bill pe point nahi.'),
        ex: T('₹100: a ₹60 chai earns nothing; ₹150 earns points.', '₹100: ₹60 की चाय पर कुछ नहीं; ₹150 पर पॉइंट।', '₹100: ₹60 ki chai pe kuch nahi; ₹150 pe point.') },
    points_ratio: { guide: 'offers', who: OWNER_MGR,
        t: T('Points to ₹ ratio', 'पॉइंट से ₹ का अनुपात', 'Point se ₹ ka ratio'),
        d: T('How many points make ₹1 off when the customer spends them.', 'ख़र्च करते समय कितने पॉइंट = ₹1 छूट।', 'Kharch karte waqt kitne point = ₹1 off.'),
        ex: T('10: 500 points = ₹50 off.', '10: 500 पॉइंट = ₹50 छूट।', '10: 500 point = ₹50 off.') },
    points_max_pct: { guide: 'offers', who: OWNER_MGR,
        t: T('Max % payable with points', 'पॉइंट से अधिकतम %', 'Point se max %'),
        d: T('The most of one bill that points can pay.', 'एक बिल का अधिकतम कितना हिस्सा पॉइंट से।', 'Ek bill ka max kitna hissa point se.'),
        ex: T('50%: on a ₹300 bill, points cover at most ₹150.', '50%: ₹300 के बिल पर पॉइंट से अधिकतम ₹150।', '50%: ₹300 ke bill pe point se max ₹150.') },
    points_min_redeem: { guide: 'offers', who: OWNER_MGR,
        t: T('Minimum points to redeem', 'ख़र्च के लिए न्यूनतम पॉइंट', 'Kharch ke liye minimum point'),
        d: T('A customer needs at least this many points before they can spend any.', 'ग्राहक के पास कम से कम इतने पॉइंट हों तभी ख़र्च कर सकता है।', 'Customer ke paas kam se kam itne point hon tabhi kharch kar sakta hai.'),
        ex: T('100: someone with 80 points has to wait.', '100: 80 पॉइंट वाले को रुकना होगा।', '100: 80 point wale ko rukna hoga.') },
    // Customers → Coupons
    coupon_limit: { guide: 'offers', who: T('Owner, Manager (Coupons)', 'मालिक, मैनेजर (Coupons)', 'Owner, Manager (Coupons)'),
        t: T('Usage limit', 'कितनी बार', 'Kitni baar'),
        d: T('How many times the coupon can be used in total. -1 = no limit.', 'कूपन कुल कितनी बार लग सकता है। -1 = कोई सीमा नहीं।', 'Coupon kul kitni baar lag sakta hai. -1 = koi limit nahi.'),
        ex: T('200: the 201st customer is told the coupon is used up.', '200: 201वें ग्राहक को बताया जाएगा कूपन ख़त्म।', '200: 201ve customer ko bataya jaayega coupon khatam.') },
    coupon_max: { guide: 'offers', who: T('Owner, Manager (Coupons)', 'मालिक, मैनेजर (Coupons)', 'Owner, Manager (Coupons)'),
        t: T('Maximum discount', 'अधिकतम छूट', 'Max discount'),
        d: T('A cap on % coupons so big bills do not get a huge discount.', '% कूपन पर सीमा ताकि बड़े बिल पर बहुत बड़ी छूट न हो।', '% coupon pe limit taaki bade bill pe bahut badi chhoot na ho.'),
        ex: T('10% up to ₹100: a ₹2,000 bill gets ₹100 off, not ₹200.', '10%, अधिकतम ₹100: ₹2,000 के बिल पर ₹100 छूट, ₹200 नहीं।', '10%, max ₹100: ₹2,000 ke bill pe ₹100 off, ₹200 nahi.') },
    // Menu → Customer app
    confirm_first: { guide: 'tables', who: OWNER_MGR,
        t: T('Staff confirm the first order', 'पहला ऑर्डर स्टाफ कन्फ़र्म करे', 'Pehla order staff confirm kare'),
        d: T('A table\'s first QR order waits until staff tap Confirm table, so a QR photo sent from outside cannot place orders.', 'टेबल का पहला QR ऑर्डर तब तक रुकता है जब तक स्टाफ Confirm table न दबाए, ताकि बाहर भेजी QR फ़ोटो से ऑर्डर न हो।', 'Table ka pehla QR order tab tak rukta hai jab tak staff Confirm table na dabaye, taaki bahar bheji QR photo se order na ho.'),
        ex: T('Table 5 orders: Orders shows “Confirm table” in yellow; after the tap the kitchen gets it.', 'टेबल 5 ऑर्डर करती है: Orders में पीला “Confirm table”; दबाने के बाद किचन को मिलता है।', 'Table 5 order karti hai: Orders mein peela “Confirm table”; dabane ke baad kitchen ko milta hai.') },
    accept_all: { guide: 'tables', who: OWNER_MGR,
        t: T('Accept every QR order', 'हर QR ऑर्डर स्वीकार करें', 'Har QR order accept karo'),
        d: T('Every QR order waits on the full-screen alert until a staff member taps Accept; only then the kitchen sees it. Turn off to send QR orders to the kitchen straight away.', 'हर QR ऑर्डर फ़ुल-स्क्रीन अलर्ट पर तब तक रुकता है जब तक स्टाफ Accept न दबाए; तभी किचन को दिखता है। बंद करें तो QR ऑर्डर सीधे किचन जाते हैं।', 'Har QR order full-screen alert pe tab tak rukta hai jab tak staff Accept na dabaye; tabhi kitchen ko dikhta hai. Band karo toh QR order seedha kitchen jaate hain.'),
        ex: T('Table 3 orders 2 coffees: the alert rings, the waiter taps Accept, the coffee ticket appears in Kitchen.', 'टेबल 3 दो कॉफ़ी मँगाती है: अलर्ट बजता है, वेटर Accept दबाता है, कॉफ़ी का टिकट Kitchen में आता है।', 'Table 3 do coffee mangati hai: alert bajta hai, waiter Accept dabata hai, coffee ka ticket Kitchen mein aata hai.') },
    announcement: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Announcement strip', 'सूचना की पट्टी', 'Announcement strip'),
        d: T('One short line at the top of the customer app. Empty = hidden.', 'ग्राहक ऐप के सबसे ऊपर एक छोटी लाइन। ख़ाली = छिपी।', 'Customer app ke sabse upar ek chhoti line. Khaali = chhupi.'),
        ex: T('“Live music Friday 8 pm 🎶”.', '“शुक्रवार रात 8 बजे लाइव म्यूज़िक 🎶”।', '“Friday raat 8 baje live music 🎶”.') },
    banners: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Banners', 'बैनर', 'Banner'),
        d: T('Pictures on the customer home screen. Each can open a dish, a category or the rewards page, and can have start and end dates.', 'ग्राहक होम स्क्रीन की तस्वीरें। हर बैनर कोई डिश, श्रेणी या रिवॉर्ड पेज खोल सकता है, और शुरू-ख़त्म की तारीख़ रख सकता है।', 'Customer home screen ki photo. Har banner koi dish, category ya rewards page khol sakta hai, aur start-end date rakh sakta hai.'),
        ex: T('“Dosa Tuesday · ₹20 off” opening the Dosa category.', '“Dosa Tuesday · ₹20 off” जो Dosa श्रेणी खोले।', '“Dosa Tuesday · ₹20 off” jo Dosa category khole.') },
    banner_art: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Banner picture', 'बैनर की तस्वीर', 'Banner ki photo'),
        d: T('Upload your own photo (best), or pick a drawn picture and a background colour. "Theme colour" follows the look the customer picked.', 'अपनी फ़ोटो डालें (सबसे अच्छा), या बनी हुई तस्वीर और पीछे का रंग चुनें। "Theme colour" ग्राहक की चुनी थीम के साथ बदलता है।', 'Apni photo daalo (sabse accha), ya bani hui picture aur peeche ka rang chuno. "Theme colour" customer ki chuni theme ke saath badalta hai.'),
        ex: T('"2 for ₹299" with the drawn iced coffee on Espresso.', '"2 for ₹299" के साथ बनी हुई आइस्ड कॉफ़ी, Espresso रंग पर।', '"2 for ₹299" ke saath bani hui iced coffee, Espresso rang pe.') },
    banner_times: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Show between', 'इस समय के बीच दिखाएँ', 'Is time ke beech dikhao'),
        d: T('The banner shows only between these times each day (cafe time). Empty = all day. Works together with the dates.', 'बैनर हर दिन सिर्फ़ इन समयों के बीच दिखता है (कैफ़े का समय)। ख़ाली = पूरा दिन। तारीख़ों के साथ मिलकर चलता है।', 'Banner har din sirf in times ke beech dikhta hai (cafe ka time). Khaali = poora din. Dates ke saath milkar chalta hai.'),
        ex: T('Happy hour 15:00 to 18:00: the banner appears at 3 PM and hides itself at 6 PM.', 'हैप्पी आवर 15:00 से 18:00: बैनर 3 बजे दिखता है और 6 बजे अपने-आप छिप जाता है।', 'Happy hour 15:00 se 18:00: banner 3 baje dikhta hai aur 6 baje apne aap chhup jaata hai.') },
    cx_themes: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Themes', 'थीम', 'Themes'),
        d: T('Switch on the themes customers may pick in Me → Look. The ★ theme is what new customers see first and is always on. "Make my own" builds one from your two colours.', 'वे थीम चालू करें जो ग्राहक Me → Look में चुन सकें। ★ वाली थीम नए ग्राहकों को पहले दिखती है और हमेशा चालू रहती है। "Make my own" आपके दो रंगों से थीम बनाता है।', 'Woh themes on karo jo customer Me → Look mein chun sakein. ★ wali theme naye customers ko pehle dikhti hai aur hamesha on rehti hai. "Make my own" aapke do rangon se theme banata hai.'),
        ex: T('Latte Cream ★ for the day, Espresso Glass on for night owls.', 'दिन के लिए Latte Cream ★, रात वालों के लिए Espresso Glass चालू।', 'Din ke liye Latte Cream ★, raat walon ke liye Espresso Glass on.') },
    cx_glass: { guide: 'customerapp', who: OWNER_MGR,
        t: T('Glass look', 'ग्लास लुक', 'Glass look'),
        d: T('How frosted the cards look on glass themes (Espresso, Berry, Ocean). Off = plain cards. Other themes are not affected.', 'ग्लास थीम (Espresso, Berry, Ocean) पर कार्ड कितने धुंधले काँच जैसे दिखें। Off = सादे कार्ड। बाकी थीम पर असर नहीं।', 'Glass themes (Espresso, Berry, Ocean) pe card kitne frosted dikhein. Off = saade card. Baaki themes pe asar nahi.'),
        ex: T('Medium suits most phones; Strong can look busy on cheap screens.', 'ज़्यादातर फ़ोन के लिए Medium ठीक; सस्ती स्क्रीन पर Strong भारी लग सकता है।', 'Zyadatar phone ke liye Medium theek; sasti screen pe Strong bhaari lag sakta hai.') },
    // Settings → Brand & look
    brand_colour: { guide: 'brand', who: OWNER_MGR,
        t: T('Main colour', 'मुख्य रंग', 'Main rang'),
        d: T('Used for buttons, prices and links everywhere. It must be dark enough to read white text on; paler colours are blocked.', 'हर जगह बटन, दाम और लिंक में। इतना गहरा होना चाहिए कि उस पर सफ़ेद अक्षर पढ़े जाएँ; हल्के रंग रुक जाते हैं।', 'Har jagah button, daam aur link mein. Itna gehra hona chahiye ki us pe safed akshar padhe jaayein; halke rang ruk jaate hain.'),
        ex: T('Light yellow is blocked; “Use a deeper shade” picks a readable one.', 'हल्का पीला रुक जाता है; “Use a deeper shade” पढ़ने लायक रंग चुनता है।', 'Halka peela ruk jaata hai; “Use a deeper shade” padhne layak rang chunta hai.') },
    cx_mode: { guide: 'brand', who: OWNER_MGR,
        t: T('Customer app opens in', 'ग्राहक ऐप किसमें खुले', 'Customer app kisme khule'),
        d: T('Light, dark, or the customer\'s own phone setting. Staff choose their own screen separately.', 'लाइट, डार्क, या ग्राहक के फ़ोन की सेटिंग। स्टाफ अपनी स्क्रीन अलग चुनते हैं।', 'Light, dark, ya customer ke phone ki setting. Staff apni screen alag chunte hain.'),
        ex: T('“Customer\'s phone setting”: a phone in dark mode sees the app dark.', '“Customer\'s phone setting”: डार्क मोड वाले फ़ोन पर ऐप डार्क।', '“Customer\'s phone setting”: dark mode wale phone pe app dark.') },
    // Settings → Alerts
    alert_style: { guide: 'alerts', who: OWNER,
        t: T('Alert style', 'अलर्ट का तरीका', 'Alert ka tarika'),
        d: T('Alarm: whole screen with the order and sound until someone acts on it (Accept, Take payment). Loud: rings once. Normal: shows on the bell only. Off: nothing.', 'Alarm: पूरी स्क्रीन, आवाज़ के साथ, Acknowledge तक। Loud: एक बार बजता है। Normal: सिर्फ़ घंटी पर। Off: कुछ नहीं।', 'Alarm: poori screen, awaaz ke saath, Acknowledge tak. Loud: ek baar bajta hai. Normal: sirf ghanti pe. Off: kuch nahi.'),
        ex: T('Counter laptop: New order = Alarm. Owner phone: New order = Normal.', 'काउंटर लैपटॉप: New order = Alarm। मालिक का फ़ोन: New order = Normal।', 'Counter laptop: New order = Alarm. Owner phone: New order = Normal.') },
    quiet_hours: { guide: 'alerts', who: OWNER,
        t: T('Quiet hours', 'शांत समय', 'Quiet hours'),
        d: T('During these hours this person\'s alerts stay silent, except new orders, payment requests and escalations.', 'इस समय इस व्यक्ति के अलर्ट शांत रहते हैं, सिवाय नए ऑर्डर, पेमेंट माँग और एस्केलेशन के।', 'Is waqt is vyakti ke alert shaant rehte hain, siwaay naye order, payment request aur escalation ke.'),
        ex: T('Owner 11 pm–7 am: low-stock alerts wait till morning.', 'मालिक रात 11–सुबह 7: कम स्टॉक के अलर्ट सुबह तक रुकते हैं।', 'Owner raat 11–subah 7: kam stock ke alert subah tak rukte hain.') },
    // Team → Staff logins & Roles
    exceptions: { guide: 'roles', who: OWNER,
        t: T('Exceptions', 'अपवाद (Exceptions)', 'Exceptions'),
        d: T('Give or take away one right for one person without changing their whole role.', 'पूरा रोल बदले बिना किसी एक व्यक्ति को एक अधिकार दें या हटाएँ।', 'Poora role badle bina kisi ek vyakti ko ek right do ya hatao.'),
        ex: T('Head cashier Kabir: “Give discounts” → Allow.', 'हेड कैशियर कबीर: “Give discounts” → Allow।', 'Head cashier Kabir: “Give discounts” → Allow.') },
    sensitive: { guide: 'roles', who: OWNER,
        t: T('Sensitive rights', 'संवेदनशील अधिकार', 'Sensitive rights'),
        d: T('Separate switches for salaries, cost and profit, discounts, cancelling bills, full customer phone numbers and khata over the limit.', 'वेतन, लागत और मुनाफ़ा, छूट, बिल रद्द करना, ग्राहक का पूरा नंबर और सीमा से ऊपर खाता: इनके अलग स्विच।', 'Salary, laagat aur munafa, discount, bill cancel karna, customer ka poora number aur limit se upar khata: inke alag switch.'),
        ex: T('Cashiers usually get “Give discounts” but not “See salaries”.', 'कैशियर को आमतौर पर “Give discounts” मिलता है, “See salaries” नहीं।', 'Cashier ko aam taur pe “Give discounts” milta hai, “See salaries” nahi.') },
    // Money
    profit_margin: { guide: 'reports', who: OWNER_MGR,
        t: T('Usual profit margin', 'आम मुनाफ़ा %', 'Aam margin'),
        d: T('Used only for the quick “Estimated profit” on this page. The real profit is in Reports → Profit & loss.', 'सिर्फ़ इस पेज के “Estimated profit” के लिए। असली मुनाफ़ा Reports → Profit & loss में।', 'Sirf is page ke “Estimated profit” ke liye. Asli munafa Reports → Profit & loss mein.'),
        ex: T('30%: ₹10,000 sales → about ₹3,000 estimated profit.', '30%: ₹10,000 बिक्री → लगभग ₹3,000 अनुमानित मुनाफ़ा।', '30%: ₹10,000 bikri → lagbhag ₹3,000 estimated munafa.') },
    profit_target: { guide: 'reports', who: OWNER_MGR,
        t: T('Profit target', 'मुनाफ़ा लक्ष्य', 'Munafa target'),
        d: T('Your profit goal for the week or month. The report shows profit so far and a forecast for the whole period.', 'हफ़्ते या महीने का मुनाफ़ा लक्ष्य। रिपोर्ट अब तक का मुनाफ़ा और पूरे समय का अनुमान दिखाती है।', 'Hafte ya mahine ka munafa goal. Report ab tak ka munafa aur poore period ka forecast dikhati hai.'),
        ex: T('₹60,000 a month, ₹40,000 by day 20 of 30 → forecast ₹60,000 (100% of target).', '₹60,000 महीना, 30 में से 20 दिन में ₹40,000 → अनुमान ₹60,000 (लक्ष्य का 100%)।', '₹60,000 mahina, 30 mein se 20 din mein ₹40,000 → forecast ₹60,000 (target ka 100%).') },
    devices: { guide: 'screens', who: OWNER_MGR,
        t: T('Devices', 'डिवाइस', 'Devices'),
        d: T('Every counter, kiosk and kitchen screen that opened the app. Turning one off frees a kiosk slot; that screen must be set up again to be used.', 'हर काउंटर, कियोस्क और किचन स्क्रीन जिसने ऐप खोला। बंद करने से कियोस्क स्लॉट ख़ाली होता है; दोबारा इस्तेमाल के लिए स्क्रीन फिर से सेट करनी होगी।', 'Har counter, kiosk aur kitchen screen jisne app khola. Band karne se kiosk slot khaali hota hai; dobara use ke liye screen phir se set karni hogi.'),
        ex: T('Broken tablet K2 “Last used 40 days ago” → Turn off.', 'ख़राब टैबलेट K2 “Last used 40 days ago” → Turn off।', 'Kharab tablet K2 “Last used 40 days ago” → Turn off.') },
};
