// Words on the phone Orders and Kitchen screens in English, Hindi and Hinglish
const T = (en, hi, hinglish) => ({ en, hi, hinglish });

export const W = {
    action: T('Needs action', 'काम बाकी', 'Kaam baaki'),
    cooking: T('Cooking', 'बन रहा', 'Ban raha'),
    ready: T('Ready', 'तैयार', 'Ready'),
    unpaid: T('Unpaid', 'पैसे बाकी', 'Paise baaki'),
    all: T('All', 'सभी', 'Sab'),
    hint: T('Swipe a card right for its next step · tap it for more', 'अगले कदम के लिए कार्ड दाईं ओर खिसकाएँ · ज़्यादा के लिए दबाएँ', 'Agla step: card right swipe karo · zyada ke liye dabao'),
    noOrders: T('No open orders right now.', 'अभी कोई खुला ऑर्डर नहीं।', 'Abhi koi open order nahi.'),
    allClear: T('Nothing here. All clear.', 'यहाँ कुछ नहीं। सब साफ़।', 'Yahan kuch nahi. Sab clear.'),
    waitingStaff: T('Waiting for staff', 'स्टाफ का इंतज़ार', 'Staff ka intezaar'),
    wantsUpi: T('Wants UPI', 'UPI से देगा', 'UPI se dega'),
    payingCounter: T('Paying at counter', 'काउंटर पर देगा', 'Counter pe dega'),
    paid: T('Paid', 'पैसे मिले', 'Paid'),
    walkIn: T('Walk-in', 'वॉक-इन', 'Walk-in'),
    table: T('Table', 'टेबल', 'Table'),
    confirmTable: T('Confirm table', 'टेबल कन्फ़र्म', 'Table confirm'),
    confirm: T('Confirm', 'कन्फ़र्म', 'Confirm'),
    start: T('Start', 'शुरू करें', 'Shuru karo'),
    markReady: T('Mark ready', 'तैयार है', 'Ready hai'),
    served: T('Served', 'दे दिया', 'De diya'),
    makeBill: T('Make bill', 'बिल बनाएँ', 'Bill banao'),
    takePayment: T('Take payment', 'पैसे लें', 'Paise lo'),
    kot: T('KOT', 'KOT', 'KOT'),
    printBill: T('Print bill', 'बिल प्रिंट', 'Bill print'),
    bill: T('Bill', 'बिल', 'Bill'),
    wholeTable: T('Whole table', 'पूरी टेबल', 'Poori table'),
    move: T('Move', 'टेबल बदलें', 'Table badlo'),
    cancelOrder: T('Cancel this order…', 'यह ऑर्डर रद्द करें…', 'Yeh order cancel karo…'),
    minAgo: T('min ago', 'मिनट पहले', 'min pehle'),
    total: T('Total', 'कुल', 'Total'),
    balance: T('Balance', 'बाकी', 'Baaki'),
    heldNote: T('First order on this table. Check someone is sitting there, then confirm. The kitchen gets it after that.',
        'इस टेबल का पहला ऑर्डर। देखें कोई बैठा है, फिर कन्फ़र्म करें। उसके बाद किचन को मिलेगा।',
        'Is table ka pehla order. Dekho koi baitha hai, phir confirm karo. Uske baad kitchen ko milega.'),
    status: {
        pending: T('New', 'नया', 'Naya'), confirmed: T('Confirmed', 'कन्फ़र्म', 'Confirm'), preparing: T('Cooking', 'बन रहा', 'Ban raha'),
        ready: T('Ready', 'तैयार', 'Ready'), served: T('Served', 'दे दिया', 'De diya'), bill_requested: T('Wants bill', 'बिल माँगा', 'Bill maanga'),
        bill_generated: T('Bill given', 'बिल दिया', 'Bill diya'),
    },
    // Kitchen
    tickets: T('tickets', 'टिकट', 'ticket'),
    oldest: T('oldest', 'सबसे पुराना', 'sabse purana'),
    hot: T('Hot kitchen', 'गरम किचन', 'Garam kitchen'),
    bar: T('Coffee bar', 'कॉफ़ी बार', 'Coffee bar'),
    cold: T('Cold', 'ठंडा', 'Thanda'),
    allReady: T('All ready', 'सब तैयार', 'Sab ready'),
    soundOn: T('Sound on', 'आवाज़ चालू', 'Sound on'),
    soundOff: T('Sound off', 'आवाज़ बंद', 'Sound off'),
    fullScreen: T('Full screen', 'पूरी स्क्रीन', 'Full screen'),
    kitchenEmpty: T('No orders in the kitchen. New orders appear here with a sound.', 'किचन में कोई ऑर्डर नहीं। नए ऑर्डर आवाज़ के साथ यहाँ आएँगे।', 'Kitchen mein koi order nahi. Naye order sound ke saath yahan aayenge.'),
    stationEmpty: T('No orders for this station.', 'इस स्टेशन के लिए कोई ऑर्डर नहीं।', 'Is station ke liye koi order nahi.'),
};
